### ISSUE TITLE
Message room should have #/@ prefix

### ISSUE THREAD

**Issue by kballard** [slackapi/hubot-slack#119]
It appears that messages created by this adaptor do not use the `#`/`@` prefix on rooms. Is there some reason for this? It would seem appropriate to have those prefixes on the names, so rooms can be printed sanely, and so scripts that expect the Slack adaptor can tell the difference between channels and IMs.

**Comment by DEGoodmanWilson** [comment]
There is clearly going to be some kind of interaction with #136 that will have to be worked out…

**Comment by johnagan** [comment]
I don't believe this is still an issue. Feel free to reopen if so.
