### ISSUE TITLE
Get notified of user editing message

### ISSUE THREAD

**Issue by mcdan** [slackapi/hubot-slack#143]
I couldn't find an issue for this and maybe I can do it already but how can the bot know when a user has edited their message. For example someone types a command which has a spelling error in to:

hubot iamge me foobar
::hubot does not respond::
The user then edits their message to say:

hubot image me foobar
::hubot still doesn't respond::

It would be nice if the hubot script could get least get a different message type when the user performs an edit.

**Comment by paulhammond** [comment]
The hubot adapter already has access to this data (a `message_changed` message gets sent to it whenever a message is updated) so this just needs some code to be written. Pull requests are welcome!

**Comment by mcdan** [comment]
Nice, I'll have a look at trying to build it out. thanks.

**Comment by johnagan** [comment]
nothing to do here.
