### ISSUE TITLE
Allow bots to utilize @channel/@group when it it restricted for normal users

### ISSUE THREAD

**Issue by ShadowRAM** [slackapi/hubot-slack#149]
We have @channel and @group restricted to admins and owners.  Before using the IRC adapter I made the bot's account an admin and it was able to trigger notifications using those commands.  However for better performance I switched to the slack adapter which is considerably more responsive and you can't grant "Bot" accounts that level of access.  Is there any way to add that functionality for hubot accounts or trigger those notifications via the API?

**Comment by paulhammond** [comment]
That's a great question! I'm going to share this request with the rest of the team and see what they think about it.

**Comment by ShadowRAM** [comment]
Thanks.  Being able to grant admin or set the @channel/@group command to be usable my mods and bots would probably be a preferable solution to an API change now that I read that again! :)

**Comment by BlueHatbRit** [comment]
+1 for this feature, it would be really useful for us with things like stand up alarms or general notices that may need to be cast out.

**Comment by johnagan** [comment]
Closing this because it's not a Hubot issue, but rather a Slack API request.
