### ISSUE TITLE
Add config option to ignore channels

### ISSUE THREAD

**Issue by aendra-rininsland** [slackapi/hubot-slack#15]
Hi!
Hubot's great, but it's just too damn easy to pugbomb the #general channel. To that end, I think it'd be helpful to have a config option that lets you specify Slack channels where Hubot should not respond to commands.

Seems like it'd be a fun minor dev task and I might do it for my company regardless -- let me know if you want me to submit a pull request!

**Comment by daemonsy** [comment]
For future readers, it seems that this patch has been removed. https://github.com/michaeljacobdavis/hubot-slack-whitelist-middleware seems to be the way to go

**Comment by vwbusguy** [comment]
Unfortunately, that middleware works for whitelisting but not blacklisting.  For example, I have a case where hubot is being triggered by other Slack app bots and would like to blacklist those.  I understand that asking to ignore all app/bots would be a different issue, but a simple blacklist ignore would really solve it in our case.

**Comment by aoberoi** [comment]
@vwbusguy: i'd suggest forking the whitelist middleware and making one that does the blacklist too. it seems like the author hasn't been addressing PRs, so you might just want to create a new package that does both these features. i'd also suggest merging in the PRs from that repo that look good to you.

**Comment by vwbusguy** [comment]
Actually, I ended up just writing my own blacklist middleware. I might publish it later on this week if I have time.

**Comment by aoberoi** [comment]
cool! let us know if you do 🎉

**Comment by patcon** [comment]
If you're busy, you could just copy it into a gist, link it here, and let someone else do the packaging work ;)
