### ISSUE TITLE
Automatically make a send() with a "\n" be converted to a paste

### ISSUE THREAD

**Issue by eric** [slackapi/hubot-slack#17]
Our campfire hubot plugins often send pastes by including a `\n` in a `send()`, but in slack it doesn't show up as a paste (and can often flood the room).

**Comment by pixelrebel** [comment]
Just checking in on this. Are snippets supported at this time?

**Comment by technicalpickles** [comment]
Another option: when multiple lines are detected, wrap it up in an attachment using `customMessage`. Attachments only show the first 5 lines by default, so that'd prevent flooding.

**Comment by technicalpickles** [comment]
I put a fix for this together over at https://github.com/slackhq/hubot-slack/issues/235 if anyone wants to try it.

> Are snippets supported at this time?

Worth noting that snippets are just file uploads under the hood, and as talked about in https://github.com/slackhq/hubot-slack/issues/62, files.upload isn't supported for [bot users](https://api.slack.com/bot-users).

**Comment by kiliankoe** [comment]
#62 has since been updated that `files.upload` is now supported for bot users. Just FYI 😊

**Comment by DEGoodmanWilson** [comment]
I'm of two minds about this. On one hand, a message with line breaks in it is a perfectly valid message—on the other, as has been noted, it is _different_ behavior from what is often expected. What if we included an optional flag to indicate that a message should instead be uploaded as a snippet? I'm not entirely in love with this idea, but I am very reluctant to change the default behavior.

**Comment by johnagan** [comment]
I'm closing this because I doesn't seem like something we're going to take on. It seems to be a hot topic (a year ago), so if folks still feel strongly about it, let's discuss in a PR on how it might work. Thanks!
