### ISSUE TITLE
Room membership seems to get stale

### ISSUE THREAD

**Issue by jayjanssen** [slackapi/hubot-slack#175]
I have a bot that does an action based on current channel members.  

```
    channel = msg.robot.adapter.client.getChannelGroupOrDMByName chan_name
    for uid in channel.members
        ... do something
```

I just saw a situation where the list of members in a channel were out of date.  I haven't fully debugged it to see if i can reproduce it yet, but I wanted to log it at least for now.

**Comment by davidkassa** [comment]
I think I'm running into this now. Still investigating.

**Comment by johnagan** [comment]
I believe this was corrected in the updated SDK. Please reopen if it's still a problem.
