### ISSUE TITLE
hubot-slack with hubot-redis-brain `[RangeError: Maximum call stack size exceeded]`

### ISSUE THREAD

**Issue by ptierno** [slackapi/hubot-slack#212]
When using `redis` to persist `hubot`'s brain. I am receiving the following error

```
[Tue Jul 14 2015 12:00:15 GMT-0400 (EDT)] INFO Slack client now connected
[Tue Jul 14 2015 12:00:15 GMT-0400 (EDT)] DEBUG Loading scripts from /opt/hubot/scripts
...
...
...
[Tue Jul 14 2015 12:00:16 GMT-0400 (EDT)] INFO Using default redis on localhost:6379
...
...
...
[Tue Jul 14 2015 12:00:16 GMT-0400 (EDT)] DEBUG Successfully connected to Redis
[Tue Jul 14 2015 12:00:16 GMT-0400 (EDT)] INFO Data for hubot brain retrieved from Redis
[Tue Jul 14 2015 12:00:25 GMT-0400 (EDT)] ERROR undefined
[RangeError: Maximum call stack size exceeded]
```

`Redis` never gets populated with the data from hubot's brain. I believe this is occuring in either the `@.loggedIn` method when calling `@.userChange` in the for loop over the users. Or in `@.brainLoaded`, during the same loop.

There is no issues when not trying to persist using redis.

Thanks

**Comment by DEGoodmanWilson** [comment]
Are you still having this problem? I'm going to put this on my plate to investigate.

**Comment by jaitaiwan** [comment]
We saw the same thing recently. Move from node 0.10 to 4.1.x and that seems to have made the issue disappear.

**Comment by DEGoodmanWilson** [comment]
Interesting…any idea why that would have solved the issue?

**Comment by jaitaiwan** [comment]
The range call exceeded was coming from net.js in the node core Lib.






On Tue, Jul 26, 2016 at 2:32 AM +1000, "Don Goodman-Wilson" <notifications@github.com> wrote:












Interesting…any idea why that would have solved the issue?

**Comment by DEGoodmanWilson** [comment]
It is worth noting that `@slack/client`, upon which `hubot-slack` depends requires at least Node 0.12. Hrm…

**Comment by ptierno** [comment]
upgrading node didn't fix the issue for me...

**Comment by aoberoi** [comment]
@ptierno is this issue still affecting you in the latest versions of this adapter? we made some major changes in #381 (released in jan 2017) that started loading users into the hubot brain once again.

**Comment by aoberoi** [comment]
i don't typically like closing issues without feedback from the OP, but i think in this case its appropriate. if you do experience this issue, feel free to comment and we will re-open.

**Comment by jpcope** [comment]
If you are like me and ended up here because you run hubot with the redis-brain + hubot-auth package(s) and found a matching `RangeError: Maximum call stack size exceeded` error message, check out https://github.com/slackapi/hubot-slack/pull/505

Each user object should not have multiple layers of slack objects. We had one user with 45k layers deep of dictionary slack keys. The default nodejs JSON.parse cannot handle json that deep.

Upgrading and clearing the brain key from redis fixed our issue. Make sure you backup your brain before you clear it.
