### ISSUE TITLE
Warn when trying to send custom message with > 10 attachments

### ISSUE THREAD

**Issue by technicalpickles** [slackapi/hubot-slack#239]
I was speaking with Slack customer care about some other hubot-related questions, and I asked about a limit of attachments in a message:

> I checked with the integrations team and it looks like we don't currently have a limit on the number of attachments. However, we'd recommend keeping it below 10, as we might reconsider imposing one in the future, depending on what would make the most sense on both ends.

We could check for the number of attachments in `customMessage` and log a warning if it's more than 10.

**Comment by DEGoodmanWilson** [comment]
A+++ good idea, would implement again.

**Comment by johnagan** [comment]
I'm closing this in favor of the platform's 20 attachment limit.
