### ISSUE TITLE
Codeblocks Max Chars

### ISSUE THREAD

**Issue by pixelrebel** [slackapi/hubot-slack#240]
The maximum characters allowed for codeblock formatting is significantly less than if the message is sent via http or via hubot-xmpp.  The limit imposed from a post via hubot-xmpp is around 16309 characters.  I think the limit imposed but hubot-slack is around 4000.  

Anyway we can increase this limit?

**Comment by evansolomon** [comment]
The 4k character limit is actually suggested in Slack's API docs here https://api.slack.com/rtm under the "Limits" section. That said, the actual limit is in bytes (16k) not characters, and the suggested limit is intended to make the worst case scenario (a message composed entirely of multi-byte characters) safe. The handling could probably be more nuanced than just using a 4k character limit.

**Comment by pixelrebel** [comment]
@evansolomon, I guess that I must be sending 1-byte characters in my hubot-xmpp implementation?  

My bot posts a nicely formatted text table that provides a status of our storage systems.   I'm not sure why, but the limit seems a bit arbitrary.  I could split the table into separate code blocks, but it's not as intuitive to read.  I don't think a snippet is the better alternative for me either.  Also, AFAIK the API doesn't provide a way to post snippets.

**Comment by evansolomon** [comment]
> I guess that I must be sending 1-byte characters in my hubot-xmpp implementation?

Something like that. Or just any kind of string that is in total less than 16k bytes. But if it's just a table then yea it's probably all one byte characters.

> the limit seems a bit arbitrary

I suppose it is, but it's Slack's API :) It's reasonable for there to be *some* limit, so pretty much any particular one is going to be sort of arbitrary.


Maybe a reasonable change would be to check the byte length of the message (`Buffer.byteLength(str)`) and don't alter it if it's under 16k bytes. If it's over 16k bytes then things get a little more complicated, but maybe in that case falling back to the 4k character splits (as it currently works) is okay.

**Comment by pixelrebel** [comment]
>Maybe a reasonable change would be to check the byte length of the message (Buffer.byteLength(str)) and don't alter it if it's under 16k bytes. If it's over 16k bytes then things get a little more complicated, but maybe in that case falling back to the 4k character splits (as it currently works) is okay.

I like this suggestion.  However, if this adapter is to comply with the API guidelines, I suppose the current implementation (hard 4K limit on characters) is the correct one.  :(

**Comment by technicalpickles** [comment]
I started a pull request over at https://github.com/slackhq/hubot-slack/pull/236 that switches to using `chat.postMessage` instead of the RTM API, but as a side effect, raises the limit to 8K.

**Comment by technicalpickles** [comment]
> My bot posts a nicely formatted text table that provides a status of our storage systems.

@pixelrebel one thing I've run into specifically with tabular data is that even with code blocks, the preformatted text is word-wrapped, which makes wide tables impossible to read.

**Comment by pixelrebel** [comment]
>the preformatted text is word-wrapped, which makes wide tables impossible to read.

@technicalpickles Yeah, this is an issue I haven't really addressed yet.  RIP mobile :)

**Comment by technicalpickles** [comment]
> Also, AFAIK the API doesn't provide a way to post snippets.

Snippets are file uploads under the hood, and bots don't have access to the `file.upload` API. cc https://github.com/slackhq/hubot-slack/issues/62 for some more discussion around that.

**Comment by pixelrebel** [comment]
@technicalpickles I had an issue with the `files.upload` API call.  I'm not sure how to unfurl the text file into the user-friendly display (i.e. Expand, View Raw, Share, Download etc).  I don't think it's possible.  I just post the upload results as `<#{fobj.file.url_download}|#{fobj.file.title}>`.  Which isn't a very elegant way to share an uploaded file.  I also don't like how permissions are handled on files uploaded via this method. 
I'm thinking that these are the reasons why slack is denying bot uploads.  Maybe it's just not totally ready yet.

**Comment by DEGoodmanWilson** [comment]
This is now a hard limit, and the reason is because it really messes up message formatting on our mobile clients. We now recommend breaking up long messages into multiple messages—in many cases the results will be visually indistinguishable (since that what we do internally _anyway_). Will check that this is enforced in code.

**Comment by leschekfm** [comment]
@DEGoodmanWilson as long messages are broken up internally anyway:
Is there maybe a function / code snippet that we could reuse for that?

**Comment by DEGoodmanWilson** [comment]
What you say is true, but it is better not to rely on that, as for messages over about 5KB, bad things happen to your message. Best to handle it here.

**Comment by johnagan** [comment]
Closing because I don't believe there is anything for us to do here. Feel free to open a PR with desired output if I'm wrong.
