### ISSUE TITLE
Get the post information when sending a message with attachment

### ISSUE THREAD

**Issue by tleunen** [slackapi/hubot-slack#255]
Is there a way to get the post information when sending a message with attachment (using the event emitter)?

**Comment by evansolomon** [comment]
Can you explain a bit more about what you mean by post information?

**Comment by tleunen** [comment]
When a message is published, it's possible to get its timetstamp and the posted message actually. I'm trying to get that information

**Comment by evansolomon** [comment]
I still am having trouble figuring out exactly what you want to do. Is this a specific message you are sending? Or do you want all messages that are sent in your Slack team?

**Comment by tleunen** [comment]
I want to keep track of the messages the bot is sending, to be able to update them.
But to update them, the timestamp is needed.

**Comment by DEGoodmanWilson** [comment]
Unsure if this is a Hubot limitation or a missing feature with `hubot-slack`, will investigate.

**Comment by aoberoi** [comment]
i believe the change in #440 would resolve this issue. you would be able to supply a callback to `send` and `reply` which carries this post information.

i'm closing this as a duplicate of that issue.
