### ISSUE TITLE
Cannot find module 'hubot'

### ISSUE THREAD

**Issue by mspangler** [slackapi/hubot-slack#28]
I'm installing Hubot to Heroku & I'm following the instructions outlined on the hubot-slack page but when I deploy to Heroku I get the following error:

```
ERROR Cannot load adapter slack - Error: Cannot find module 'hubot'
```

Is there something I'm doing wrong?  In the dependencies section in my package.json file I have:

```
"hubot-slack": "1.5.2"
```

and my Procfile looks like:

```
web: bin/hubot --adapter slack
```

**Comment by glebpopoff** [comment]
Make sure to install the module globally: sudo npm install **-g** hubot-slack --save
I was dealing with the same issue and installing the module globally solved it.

**Comment by aurelien-git** [comment]
Hi, I got that error too and do the sudo npm install -g hubot-slack --save
:~/hubot$ sudo npm install -g hubot-slack --save
[sudo] password for aurelien: 
npm http GET https://registry.npmjs.org/hubot-slack
npm http 304 https://registry.npmjs.org/hubot-slack
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/slack/client
npm http 304 https://registry.npmjs.org/lodash
npm http 404 https://registry.npmjs.org/slack/client
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.7.6-100.fc23.x86_64
npm ERR! command "node" "/bin/npm" "install" "-g" "hubot-slack" "--save"
npm ERR! cwd /home/aurelien/hubot
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aurelien/hubot/npm-debug.log
npm ERR! not ok code 0

**Comment by hardreggaecafe** [comment]
@evansolomon Hi I've got same errors above( @aurelien-git ). No matter how much I tried to install hubot-slack adapter, I failed. 
How should I do?
Here's related info.
hubot 2.19.0
npm 1.3.6
coffee 1.11.1

**Comment by hardreggaecafe** [comment]
I figured out by myself.
`sudo npm install npm -g`
should works.
