### ISSUE TITLE
Move help text to a snippet

### ISSUE THREAD

**Issue by unstablereality** [slackapi/hubot-slack#297]
When a lot of scripts and features have been added, hubot's help response can grow very large. Slack has the ability to create text snippets which are collapsed by default. Why not push the results of `hubot help` to a snippet to prevent spamming the channel in the event that the help response is too large?

**Comment by johnagan** [comment]
You're welcome to present this in a PR if this is still a request and we can review your ideas here. Closing this issue in the meantime since it's been hanging out there for a bit.
