### ISSUE TITLE
Http get() working locally, not on Slack.

### ISSUE THREAD

**Issue by AjinkyaBapat** [slackapi/hubot-slack#300]
I have written a simple script with **.get()** in it.
It works perfectly fine when i run it with local Hubot.
But while running it on Slack, it doesnt gives any response.

Can anyone suggest anything for this ?

**My code snippet is like this**

module.exports = (robot) ->
  robot.respond /Show me the details of my flow (.*)/i, (msg) ->
    flowid = escape(msg.match[1])
    msg.http("https://16.164.156.137:8443/oo/rest/v1/flows/#{flowid}")
      .get() (err, res, body) ->
        try
          json = JSON.parse(body)
          msg.send "   flow name: #{json.name}\n
     path: #{json.path}\n
       description: #{json.description}\n
    version: #{json.version}\n
  cpName: #{json.cpName}\n"
        catch error
          msg.send "Flow not found."

**Comment by DEGoodmanWilson** [comment]
I'm sorry to say that I do not quite understand the question. Could you tell me more about what you were expecting, and where things have gone wrong?

**Comment by johnagan** [comment]
Closing since this has gone unanswered.
