### ISSUE TITLE
SlackBot runs userChange on all users every time a value is set in the brain

### ISSUE THREAD

**Issue by mapitman** [slackapi/hubot-slack#305]
I am setting a lot of data in the robot.brain and I noticed it was taking about 20 seconds to finish. in `slack.coffee`, it attaches to the `loaded` event on the brain and runs through all the users and resets some data about the users. I believe the expected behavior is to run this once when the brain is first loaded. However, that event fires every time a value is stored in the brain. This is causing the ping to timeout because it is blocked for ~20 seconds.  
I think it should check that it is the first time loaded and only fire then.

**Comment by johnagan** [comment]
I believe this is resolved in #381

**Comment by mapitman** [comment]
Yes, when the adapter was changed to use the SDK, this issue was fixed.
