### ISSUE TITLE
No response in Slack

### ISSUE THREAD

**Issue by vaishalipavashe** [slackapi/hubot-slack#330]
This is fresh install of stackStorm where st2chatops/hubot is installed as part of stackstorm. There is no error/warning observed in logs but I dont get any response back in slack channel.  Attaching log and st2chatops.env.

Jul 26 16:12:04 stackstorm systemd[1]: Stopped StackStorm service st2chatops.
Jul 26 16:12:21 stackstorm systemd[1]: Started StackStorm service st2chatops.
Jul 26 16:12:21 stackstorm systemd[1]: Starting StackStorm service st2chatops...
Jul 26 16:12:38 stackstorm hubot[2441]: [Tue Jul 26 2016 16:12:38 GMT-0400 (EDT)] DEBUG Loading adapter slack
Jul 26 16:12:41 stackstorm hubot[2441]: [Tue Jul 26 2016 16:12:41 GMT-0400 (EDT)] INFO Connecting...
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] INFO Logged in as vp, but not yet connected
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] INFO Slack client now connected
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Loading scripts from /opt/stackstorm/chatops/scripts
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Loading scripts from /opt/stackstorm/chatops/src/scripts
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Loading hubot-scripts from /opt/stackstorm/chatops/node_modules/hubot-scripts/src
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Loading external-scripts from npm packages
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] INFO Using ST2_API_KEY as authentication. Expiry will lead to bot exit.
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Using slack post data handler.
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Parsing help for /opt/stackstorm/chatops/node_modules/hubot-stackstorm/scripts/st
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] INFO Loading commands....
Jul 26 16:13:13 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:13 GMT-0400 (EDT)] DEBUG Parsing help for /opt/stackstorm/chatops/node_modules/hubot-help/src/help.coffee
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy <repo_name> [packs <packs>] [branch <branch=master>] -
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy {{repo_name}} packs {{packs}} branch {{branch}} - Down
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy {{repo_name}} packs {{packs}} - Download StackStorm pa
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy <repo_name> [branch <branch=master>] - Download StackS
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy {{repo_name}} branch {{branch=master}} - Download Stac
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack deploy {{repo_name}} - Download StackStorm packs via ChatOps
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: pack info {{pack}} - Get StackStorm pack information via ChatOps
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: show git clone {{repo_name}} - Show the Git clone command for a gi
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} actions - List available StackStorm action
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} actions from {{ pack }} - List available S
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 get execution {{ id }} - Retrieve details for a single executi
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 show execution {{ id }} - Retrieve details for a single execut
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 executions get {{ id }} - Retrieve details for a single execut
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 executions show {{ id }} - Retrieve details for a single execu
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} executions - List available StackStorm exe
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} executions with status {{ status }} - List
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} executions for action {{ action }} - List
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 re-run execution {{ id }} - Re-run an action execution.
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 executions re-run {{ id }} - Re-run an action execution.
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} rules - List available StackStorm rules.
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} rules from {{ pack }} - List available Sta
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} sensors - List available StackStorm sensor
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] DEBUG Added command: st2 list {{ limit=10 }} sensors from {{ pack }} - List available S
Jul 26 16:13:14 stackstorm hubot[2441]: [Tue Jul 26 2016 16:13:14 GMT-0400 (EDT)] INFO 21 commands are loaded

st2chatops.env:
export HUBOT_ADAPTER=slack
export HUBOT_SLACK_TOKEN=xxxxxxxx
export HUBOT_SLACK_EXIT_ON_DISCONNECT=1

**Comment by DEGoodmanWilson** [comment]
It's reporting being connected. My guess is that your problem isn't with the Slack adapter? Just to verify, _when running_, does the bot show up in slack with a green dot next to its name in the user list on the left of the Slack main window? That green dot means Slack sees it as connected. If it is an empty gray circle, then this is a problem with the Slack adapter.

**Comment by aoberoi** [comment]
@vaishalipavashe if you're still experiencing this issue, please let us know. we need some more information to make progress. if you can provide us the code in your scripts, that would be helpful.
