### ISSUE TITLE
brain.users lacks user.name as it equals user.id

### ISSUE THREAD

**Issue by sebastiandero** [slackapi/hubot-slack#348]
- [x ] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x ] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [ x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

The robot.brain.users list contains elements that should contain a name and id, as the slack adapter does not override them the name always equals the id.
as seen in the constructor the id is set to the name(from the hubot source: user.coffee)

```
constructor: (@id, options = {}) ->
    for k of (options or {})
      @[k] = options[k]
    @['name'] ||= @id.toString()

```

but as you can see, in the campfire.coffee adapter, also from the hubot source the name is overriden:

```
withAuthor = (callback) ->
      (id, created, room, user, body) ->
        bot.User user, (err, userData) ->
          if userData.user
            author = self.robot.brain.userForId(userData.user.id, userData.user)
            userId = userData.user.id
            self.robot.brain.data
              .users[userId].name = userData.user.name
            self.robot.brain.data
              .users[userId].email_address = userData.user.email_address
            author.room = room
            callback id, created, room, user, body, author
```

The slack adapter lacks this functionality and therefore causes unnecessary headaches.
#### Reproducible in:

hubot-slack version: v4.0.2 
### Expected result:

robot.brain.users.[position].name should return the username 
### Actual result:

robot.brain.users.[position].name should return the id

**Comment by onbjerg** [comment]
Any news on this? Really annoying that my bot replies to me with my ID and not my name.

**Comment by d3vex** [comment]
Seems that there is a relation to #326

**Comment by johnagan** [comment]
closing in favor of #381
