### ISSUE TITLE
No response from Hubot

### ISSUE THREAD

**Issue by bilke** [slackapi/hubot-slack#35]
I successfully deployed Hubot to Heroku and from the logs it seems fine but I get no response when I ping Hubot `@hubot: help` although the message arrives on Hubots side:

``` bash
$ heroku logs
...
2014-02-21T15:41:07.797660+00:00 app[web.1]: Incoming message received
```

Do you have any idea how I can debug this further?

**Comment by db42** [comment]
Try `<hubot-botname> help` or `<hubot-botname>: help`
