### ISSUE TITLE
robot.brain.users is empty

### ISSUE THREAD

**Issue by cesarvarela** [slackapi/hubot-slack#352]
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

Running the https://www.npmjs.com/package/hubot-brain-inspect script shows that the users array is empty.
#### Reproducible in:

latest hubot-slack v4.0.2  deployed to Heroku
### Expected result:

a list of users 
### Actual result:

`{ users: {}, _private: {}, ambushes: {} }`

Locally seems to be working: 

`robo> { users: { '1': User { id: '1', name: 'Shell', room: 'Shell' } }, _private: {} }`

**Comment by mose** [comment]
I have the feeling this is a deliberate design. All the user object is fed by slack, updated on slack, and anything stored in brain for user would be subject to split-brain syndrome (like name change in slack and not in brain). 

The issue I see is that there are various plugins that rely on existence of user in the brain for storing user extra information. There seem to be a trend towards considering this a bad practice. 

But I wonder how realistic it is to expect all plugins to 'behave'. Maybe we could think of a hubot-slack-users new plugin that would ensure some compatibility and keep minimal user information in the brain, at least to have an object with an id ?

**Comment by telemaco** [comment]
i've the same problem. Any workarround? This bug (or design decission) brokes hubot-auth and other modules that depends of it.

**Comment by DEGoodmanWilson** [comment]
This might be a bug, but it is unclear if we can do a whole lot about it, given the way the RTM API works. Might take a fair amount of work, but we should investigate this for sure!

**Comment by telemaco** [comment]
I think the problem is that this [code](https://github.com/slackapi/hubot-slack/issues/326#issuecomment-241134345) has been removed. is it posible to restore it using RTM API?
