### ISSUE TITLE
Creating a bot named "hubot" creates a dependency conflict

### ISSUE THREAD

**Issue by Roach** [slackapi/hubot-slack#354]
Creating a hubot from a directory named "hubot" results in a dependency conflict as the bot generator names the bot's package "hubot". The README should be updated with an example directory name of "myhubot" or something similar.

```
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ENOSELF

npm ERR! Refusing to install hubot as a dependency of itself

```

**Comment by DEGoodmanWilson** [comment]
Unsure that there is anything that can be done about this? We should look into it.

**Comment by aoberoi** [comment]
AFAICT this is not an issue since the commands in the docs work for me. if it still is an issue, feel free to comment with some more info.
