### ISSUE TITLE
API-posted channel links show up with # symbol stripped in hubot-slack message

### ISSUE THREAD

**Issue by bcoia** [slackapi/hubot-slack#361]
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

Since hubot-slack v4, recognized channel names have had their #'s stripped before reaching hubot, e.g. `test #test #general` becomes `test #test general`, where #general is an existing channel and #test is not. This makes it difficult for me to parse channel names without performing my own channel lookup.

Issue is very similar to #333 (which appears to be fixed now).
#### Reproducible in:

hubot-slack version: v4.0.0-v4.1.0
#### Steps to reproduce:
1. Submit message to Slack channel via API so channel names in message body (#foo) are converted to channel links (<#C12345678|foo>).
2. Examine incoming Slack messages via hubot slack connector (regex or debug)
3. Note that the channel names have had the link (and #) stripped, making it impossible to ID them as channel names.
### Expected result:

Channel names should retain their #'s as to not alter the original message.
### Actual result:
`#` 's are removed and the message is altered.
### Attachments:

<img width="236" alt="screen shot 2016-09-22 at 3 59 19 pm" src="https://cloud.githubusercontent.com/assets/1163683/18765972/92907c24-80dd-11e6-84ca-5c12f7c16a4e.png">

`[Thu Sep 22 2016 15:44:12 GMT-0500 (CDT)] DEBUG Received message: 'hubot test #test general @karsh' in channel: DM, from: karsh`

**Comment by DEGoodmanWilson** [comment]
Thanks for this report! I apologize that it has taken some time to get triaged. We'll get on this as soon as we can!
