### ISSUE TITLE
Third-party apps and clients are broken when actually wanting to be user.

### ISSUE THREAD

**Issue by ROFISH** [slackapi/hubot-slack#362]
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

Third-party client apps are broken when it comes to user name and thinks the "name" is the name of the app.

Slack always adds "bot_id" to a message if it was posted by any third-party app, whether it is a client app or a bot. https://medium.com/slack-developer-blog/api-update-new-field-in-api-responses-d23076ea2ef3#.2dtxspxte

In hubot-slack, if a "bot_id" is present, the "message.user" is ALWAYS the app and not the user. This is really annoying when multiple people are using the same app, posting "as_user", but hubot thinks the "name" is the app, regardless of user. 

This is done here: https://github.com/slackhq/hubot-slack/blob/master/src/bot.coffee#L127
#### Reproducible in:

Latest hubot-slack as of posting.
#### Steps to reproduce:
1. Send a chat.postMessage from any third-party client.
2. (Optional) Send a chat.postMessage from any third-party client as a different user. 
### Expected result:

res.message.user has the same data as sending a message using the first-party client. Different users are properly distinguished.
### Actual result:

res.message.user of any message from any user using that third-party client has the "user" of the third-party client, thus multiple users are seen as the same user. Only if "username" is present on the message or if "bot_id" is on the profile of the user than the message is bot posting, not "as_user" posting from a third-party app.
### Attachments:

> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by DEGoodmanWilson** [comment]
This is a very interesting thing that you bring up! I agree that the behavior is off. I've triaged this issue, to flag that we intend to fix it ;)

**Comment by rbroemeling** [comment]
@DEGoodmanWilson I suspect this is actually a straightforward bug in the message-handling code within `src/bot.coffee`.

Consider this snippet:

```
  message: (message) =>
    {text, user, channel, subtype, topic, bot} = message

    return if user && (user.id == @self.id) # Ignore anything we sent, or anything from an unknown user
    return if bot && (bot.id == @self.bot_id) # Ignore anything we sent, or anything from an unknown bot

    subtype = subtype || 'message'

    # Hubot expects this format for TextMessage Listener
    user = bot if bot
    user = user if user
    user = {} if !user && !bot
    user.room = channel.id
```

`user = bot if bot` <-- if we're a bot, record that as our user.
`user = user if user` <-- except if we're a user, record THAT as our user.

Except we already over-wrote `user` on the line above, so `user = user if user` is a complete no-op.

What I would expect this stanza to be is more like this:
```
# no need to register user = user, since it's a no-op.
user = bot if !user && bot
user = {} if !user
user.room = channel.id
```

**Comment by rbroemeling** [comment]
@ROFISH Just a ping to let you know that the above PR fixes this hubot-slack behaviour, if you're interested in pulling it in to your hubot.
