### ISSUE TITLE
Is user.email_address property deprecated?

### ISSUE THREAD

**Issue by christopherRiddersater** [slackapi/hubot-slack#367]
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

After upgrading from 3.4.2 to 4.2.1 the message.user.email_address attribute seem to have moved to message.user.profile.email.

Since there seem to be a few scripts out there that uses the user.email_address property, I just wanted to make sure this is the way it's supposed to be before starting to rewrite them.
I was assuming that message.user.email_address was supposed to be there regardless of adapter (if applicable of course), is that assumption correct?
#### Reproducible in:

hubot-slack 4.2.1
OS version(s): CentOS 7
#### Steps to reproduce:

Code that worked in 3.4.2 (but not in 4.2.1):
robot.respond /show my email$/i, (res) ->
    email = res.message.user.email_address
    res.send "This is your email: #{email}."

Code that works in 4.2.1:
robot.respond /show my email$/i, (res) ->
    email = res.message.user.profile.email
    res.send "This is your email: #{email}."
### Expected result:

This is your email: myemail@example.com
### Actual result:

This is your email: undefined

**Comment by DEGoodmanWilson** [comment]
There isn't a whole lot of enforcement of convention in Hubot land. The `message.user` object mirrors the structure of what Slack hands to the bot, so you are correct that the email address is to be found in `message.user.profile.email`. If you think it should also appear in `message.user.email_address` because of Hubot conventions, we welcome PRs! ;)
