### ISSUE TITLE
create snippet

### ISSUE THREAD

**Issue by thorro** [slackapi/hubot-slack#368]
I have lots of output from hubot command, floods the channel, so I want to display it as a snippet. How to accomplish that? Can't find it in docs anywhere. I've read snippets are actually file uploads and hubot-slack supports those from 4.0 onwards. 

Any idea or example would be most welcome!

**Comment by DEGoodmanWilson** [comment]
This can be accomplished by calling the Slack Web API `files.upload` endpoint, and passing a `file` object in the `content` field. Set `file.mode` to `snippet`.
https://api.slack.com/methods/files.upload
https://api.slack.com/types/file

You can call the Slack Web API from the `robot.adapter.client.web` object.
http://slackapi.github.io/node-slack-sdk/basic_usage#uploading-a-file

**Comment by cipriansofronia** [comment]
There is also another option for that :point_right: https://github.com/slackapi/hubot-slack/issues/445#issuecomment-451619375
