### ISSUE TITLE
Incomplete sentence on documentation

### ISSUE THREAD

**Issue by JennieOhyoung** [slackapi/hubot-slack#377]
First sentence on https://slackapi.github.io/hubot-slack/ seems to be incomplete 👇 

<img width="756" alt="screen shot 2016-11-18 at 10 12 23 am" src="https://cloud.githubusercontent.com/assets/5386154/20441036/90147862-ad77-11e6-8394-c8e0b8ce0921.png">

**Comment by johnagan** [comment]
Hi @JennieOhyoung 👋  thanks for the issue - we'll look into it.

**Comment by aoberoi** [comment]
fixed, thanks for reporting!
