### ISSUE TITLE
Make hubot not listen to slackbot autoresponses/reminders

### ISSUE THREAD

**Issue by samkshah** [slackapi/hubot-slack#380]
I have a hubot script that "hears" for specific words and respond. However it listens to auto-response / reminder messages from slackbot. How to make sure hubot doesn't "listen" to posts from slackbot or any other bots per say.

**Comment by aoberoi** [comment]
slackbot is special, it doesn't look like a bot in the API, but it does have an identifiable user ID. other bot users can be identified by having a `user.is_bot` property with a value of `true`. my recommendation is to continue to listen for your specific words but exit the handler by returning when you know its a bot.

example:

```coffeescript
robot.hear /special phrase/i, (res) ->
  return if (res.envelope.user.id === 'USLACKBOT' || res.envelope.user.is_bot)
  // do my work
```
