### ISSUE TITLE
remove dependency on SlackClient.rtm.dataStore (MemoryStore)

### ISSUE THREAD

**Issue by aoberoi** [slackapi/hubot-slack#385]
## Description

While the SlackClient instance has access to the underlying `@slack/client`'s `RtmClient.dataStore`, using it to store data that is critical to the operation of this adapter is not wise. The `dataStore` abstraction isn't designed well to handle synchronization and persistence use cases. It isn't guaranteed to contain all team information (since the introduction of Enterprise Grid). Fortunately, hubot provides `robot.brain` as a useful abstraction for these purposes. We should cease to depend on the dataStore for internal operations and instead use `robot.brain` where ever it makes sense.

In v4.3.0, we began to put user data inside the robot brain. We need to take inventory of all other places where data is being fetched from the dataStore for internal operations, identify alternatives, and implement those alternatives.

Subtasks:

- [ ] announce the deprecation of the `adapter.client.rtm.dataStore` APIs.
- [ ] identify usages of dataStore originated data. determine alternative implementations. implement these changes.
- [ ] write a migration guide to help users onboard onto alternatives when they find that the API is deprecated.

Areas to be refactored:
1. `SlackFormatter`: The class can be left as-is and even instantiated and referenced from `SlackClient`. However, it will never be called. It's functionality will be reimplemented as according to #456

Note: in a future version, we should deprecate the use of the `RtmClient` directly, possibly by making `SlackClient.rtm` a private property.

* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by sebastiandero** [comment]
I would suggest a simple `robot.logger.warn "You are using a deprecated access to the user list, this feature will be removed in #{version} "`
At some point maintaining both access points might lead to inconsistent data or performance.

**Comment by aoberoi** [comment]
@sebastiandero i'd rather not wrap the entire DataStore API in a method that logs before forwarding the function call into the real DataStore object. I think announcing that it is deprecated and making sure its not removed before a semver:major change should be enough. when a major change is released, we should have a migrating guide that will help users correctly update their code/scripts.

the adapter has been supporting the hubot brain since v4.3.0. i'll update the issue for reflect the remaining work.

**Comment by aoberoi** [comment]
another dependency to eliminate:

when a message arrives, its `channel` property is derived from the dataStore method `.getChannelGroupOrDMById()`. when there's no value in the cache, that property would be `undefined`. then later, that value gets set to the `room` property of the message, and is operated on further:

https://github.com/slackapi/hubot-slack/blob/7add9cae09a571523b0201c78ca0b1a36c6b26c2/src/bot.coffee#L173-L179

**Comment by aoberoi** [comment]
will be fixed by #465

**Comment by shanedewael** [comment]
Fixed by #465 🎉
