### ISSUE TITLE
external-scripts.json not responding in Slack

### ISSUE THREAD

**Issue by lockykeaney** [slackapi/hubot-slack#394]
When running my bot with the slack adaptor, the external-scripts, even the ones that come packed with hubot, are not recognised or do not run. Those that I have coded myself (simple things like storing the wifi keys) can run fine.

When I run the bot in the console with `./bin/hubot` everything works as expected.

For example, I have installed the Dark Sky script to get the weather for the next day where our office is located. Running it in console I can get the desired result, but when I run it with the slack adaptor, nothing is registered. I can't tell if there is something wrong with the adaptor, or if the command has even run.

I have tried copying the whole script into it's own new .coffee file, but the problem persists.

This happens both when running from local and from Heroku.

**Comment by aoberoi** [comment]
hey @lockykeaney, would you mind enabling logging with `HUBOT_LOG_LEVEL=debug` and then running with the slack adapter? i'm hoping we can figure out if there's some trouble connecting to Slack.

**Comment by aoberoi** [comment]
ping @lockykeaney
