### ISSUE TITLE
Amnebivse@gmail.com 

### ISSUE THREAD

**Issue by genSud** [slackapi/hubot-slack#408]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> e.g. Description of the bug or feature

#### Reproducible in:
{project_name} version:
OS version(s):
Device(s):

#### Steps to reproduce:

1. 
2. 
3. 

### Expected result:
> e.g. What you expected to happen

### Actual result:
> e.g. What actually happened

### Attachments:
> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
Can we help you?
