### ISSUE TITLE
engine specifier for npm should reflect minimum of version 2

### ISSUE THREAD

**Issue by balaji-rajan** [slackapi/hubot-slack#410]
'slack/client' is not in the npm registry
You should bug the author to publish it
It was specified as a dependency of 'hubo

Note that you can also install from a
tarball, folder, or http url, or git url.

Windows_NT 10.0.14393
npm "install" "-g" "hubot-slack" "--save
D:\snippets\hubot
NODE -v v6.10.2
NPM -v 1.4.9
E404

**Comment by aoberoi** [comment]
@balaji-rajan it seems you have an older version of npm than what we support. you need at least `npm@2`. you should be able to run `npm install npm@latest -g` to upgrade to the latest (or if you want to be more incremental, replace `latest` with `2` for the minimum update).

i'm going to change this issue to reflect that there's a bug where we don't specify this in the `"engines"` field of the package.json.

**Comment by balaji-rajan** [comment]
@aoberoi it got resolved after updating npm package thanks
