### ISSUE TITLE
Crash related to rate limiting shortly after deploy - deploying too often?

### ISSUE THREAD

**Issue by dodgepong** [slackapi/hubot-slack#411]
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I've recently been having an issue where my hubot will crash as soon as I deploy it. I believe this happens if I deploy, then make a change, then deploy again shortly thereafter. If I wait several minutes, then deploy again, it works.

I am hosting my hubot on heroku. Here is the log:

```
Apr 12 10:02:48 app/api:  Build started by user <my email>
Apr 12 10:02:56 heroku/web.1:  Restarting 
Apr 12 10:02:56 heroku/web.1:  State changed from up to starting 
Apr 12 10:02:56 app/api:  Deploy f1d9a9b by user <my email>
Apr 12 10:02:56 app/api:  Release v309 created by user <my email>
Apr 12 10:02:57 app/api:  Release v309 created by user <my email>
Apr 12 10:02:57 app/api:  Build succeeded 
Apr 12 10:02:57 heroku/web.1:  Stopping all processes with SIGTERM 
Apr 12 10:02:57 heroku/web.1:  Process exited with status 0 
Apr 12 10:02:58 heroku/web.1:  Starting process with command `bin/hubot -a slack` 
Apr 12 10:03:04 heroku/web.1:  State changed from starting to up 
Apr 12 10:03:05 app/web.1:  [Wed Apr 12 2017 17:03:05 GMT+0000 (UTC)] INFO Logged in as <bot name> of <my slack> 
Apr 12 10:03:05 app/web.1:  [Wed Apr 12 2017 17:03:05 GMT+0000 (UTC)] INFO Slack client now connected 
Apr 12 10:03:06 app/web.1:  [Wed Apr 12 2017 17:03:05 GMT+0000 (UTC)] INFO hubot-redis-brain: Discovered redis from REDISCLOUD_URL environment variable 
Apr 12 10:03:06 app/web.1:  [Wed Apr 12 2017 17:03:05 GMT+0000 (UTC)] INFO hubot-redis-brain: Successfully authenticated to Redis 
Apr 12 10:03:06 app/web.1:  [Wed Apr 12 2017 17:03:06 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis 
Apr 12 10:03:09 app/web.1:  [Wed Apr 12 2017 17:03:09 GMT+0000 (UTC)] ERROR TypeError: Object function Number() { [native code] } has no method 'isInteger' 
Apr 12 10:03:09 app/web.1:    at handleRateLimitResponse (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:39:27) 
Apr 12 10:03:09 app/web.1:    at handleTransportResponse (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/call-transport.js:150:21) 
Apr 12 10:03:09 app/web.1:    at apply (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17) 
Apr 12 10:03:09 app/web.1:    at wrapper (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16) 
Apr 12 10:03:09 app/web.1:    at Request.handleRequestTranportRes (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/transports/request.js:20:5) 
Apr 12 10:03:09 app/web.1:    at apply (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:499:17) 
Apr 12 10:03:09 app/web.1:    at Request.wrapper [as _callback] (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:5356:16) 
Apr 12 10:03:09 app/web.1:    at Request.self.callback (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:188:22) 
Apr 12 10:03:09 app/web.1:    at Request.emit (events.js:98:17) 
Apr 12 10:03:09 app/web.1:    at Request.<anonymous> (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:1171:10) 
Apr 12 10:03:09 app/web.1:    at Request.emit (events.js:95:17) 
Apr 12 10:03:09 app/web.1:    at IncomingMessage.<anonymous> (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/request/request.js:1091:12) 
Apr 12 10:03:09 app/web.1:    at IncomingMessage.g (events.js:180:16) 
Apr 12 10:03:09 app/web.1:    at IncomingMessage.emit (events.js:117:20) 
Apr 12 10:03:09 app/web.1:    at _stream_readable.js:944:16 
Apr 12 10:03:09 app/web.1:    at process._tickCallback (node.js:458:13) 
```

I am using a free Slack, so I can understand some sort of rate-limiting, but I'm not sure what's going on in this case. I would expect some sort of more graceful error handing if deploying too often and overloading my rate limit is really the cause of this crash.

#### Reproducible in:
hubot-slack version: 4.3.3
hubot: 2.16.0
node: 0.10.x

#### Steps to reproduce:

1. Deploy Slack-connected hubot to Heroku
2. Trigger a deploy again right away
3. hubot unresponsive in Slack, error in logs

**Comment by aoberoi** [comment]
@dodgepong thanks for reporting. there's a few things i can tell from this, but mostly this has to do with you running node v0.10.x.

1. you'll need to update node for your application. this shouldn't be too hard on Heroku, you just [update your `package.json`](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version). hopefully this isn't too hard for you on your development machine or any other environment you plan on running this on. out of curiosity, what kept you on 0.10? just never had a reason to have to upgrade?

2. this package needs to update the `package.json` `"engines"` field to _at least_ 0.12.x since one of its main dependencies (`@slack/client`) depends on 0.12.x. given the [support schedule for node](https://github.com/nodejs/LTS#lts-schedule1) i'm very tempted to bump the minimum to 4.x, because nothing less even has maintenance (read: no security fixes even if they find a huge problem). i'd like to hear from folks like you who haven't updated before i decide how feasible that is. for now, i'm creating a new issue for this: #412

**Comment by aoberoi** [comment]
closing the issue, but free free to discuss here or on the linked issue.

**Comment by dodgepong** [comment]
Yes, I just never had reason to upgrade. Now it seems I do!
