### ISSUE TITLE
After initial start, any bot response is delayed by 5 minutes by loadUsers

### ISSUE THREAD

**Issue by hparadiz** [slackapi/hubot-slack#416]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> After starting the bot and issuing a command through the chat the command is visible in the log and a response is also visible almost right away but the response does not show up in the chat for about 4-5 minutes. The response shows up at almost the same time the error "ERROR Can't fetch users" is written to the log. Seems like a timeout.

#### Reproducible in:
hubot-slack version: ^4.3.4
OS version(s): OS X 10.12.4 Sierra
Device(s): MacBook Pro (15-inch, 2016)

#### Steps to reproduce:

1. Start hubot
2. Run command that has a response

### Expected result:
> Close to instant reply

### Actual result:
> Five minute delay followed by the reply showing up and the error "ERROR Can't fetch users" showing up in the log

**Comment by Akujin** [comment]
Just want to add that
https://api.slack.com/methods/users.list/test
is returning a 500 http error


Can we get some sort of timeout settings?

**Comment by Akujin** [comment]
I "fixed" this by commenting out these three lines
https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee#L56-L58

**Comment by aoberoi** [comment]
@hparadiz @G4m30v3r is this issue still occurring? i ask because it sounds much like #419 which was resolved in v4.4.0. if it is still occurring, we can try tracing the code execution to see where things slow down.

**Comment by aoberoi** [comment]
the update in #454 should also help relieve issues like this. still looking for feedback about whether or not this issue is resolved.
