### ISSUE TITLE
Add `hubot-adapter` topic

### ISSUE THREAD

**Issue by bkeepers** [slackapi/hubot-slack#417]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320

**Comment by aoberoi** [comment]
Thanks, added the topic.
