### ISSUE TITLE
Hubot.brain.set always causes a call to users.list

### ISSUE THREAD

**Issue by chapmanc** [slackapi/hubot-slack#419]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackapi/hubot-slack/blob/master/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I discovered this due to a serious performance lag on my commands which actively write to redis. It looks like https://github.com/slackapi/hubot-slack/pull/381/files#diff-d058f94b15d7abb97d499186d40867ffR57 added an event listener on robot brain 'loaded' .  This means every time I write to my brain with robot.brain.set  ( https://github.com/github/hubot/blob/master/src/brain.coffee#L31 ), I make a call to users.list.  I am not sure what the fix is here, but I was thinking we just do this once at load time or on the connected event. It might make sense for original author to weigh in here @NKMR6194 and @aoberoi  but this is slowing down performance a lot if you write to the brain several times; especially if you have a large users.list

#### Reproducible in:
{project_name} version: Hubot
OS version(s): Ubuntu 14
Device(s): all

#### Steps to reproduce:

1.  Put a console trace at https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/client.js#L149 in node_modeules/@slack/client/lib/clients/client.js
2. call robot.brain.set function and you see an outgoing request for users.list everytime.

### Expected result:
I expect that this is loaded once on connect with slack. (Open to discussion)

### Actual result:
This happens every time I call robot.brain.set(key, value)

**Comment by aoberoi** [comment]
thanks for reporting @chapmanc, this issue is very real. i'll continue conversation about the solution in your PR.
