### ISSUE TITLE
Seems like slack dropped channel information with DMs of 2+ users.

### ISSUE THREAD

**Issue by timduan** [slackapi/hubot-slack#430]
https://github.com/slackapi/hubot-slack/blob/ea6ed1fa1b12eaaadd84ae01980915bbffdf8208/src/bot.coffee#L173

So we are getting `ERROR TypeError: Cannot read property 'id' of undefined` error from the line above.

**Comment by aoberoi** [comment]
it would help if we had some more context about what exactly is happening. can you share a some steps to reproduce this, and perhaps a code snippet i could run?

the side effects sound similar to #362. might this be a duplicate?

**Comment by timduan** [comment]
Thanks for helping. I think this issue has been resolved in the newer version.
