### ISSUE TITLE
File Upload Documentation

### ISSUE THREAD

**Issue by juilianoj** [slackapi/hubot-slack#445]
### Description

I'm looking for documentation for how to upload a file.  I see that support was added in v4.0.0 for uploading files, but am unsure how to use this feature.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by juilianoj** [comment]
I realized that I must contact the robot.adapter.client.web.files.upload method.  Ticket can be closed.

Example:

`opts = {
	content: body
	channels: res.message.room
}
robot.adapter.client.web.files.upload('filename.ext', opts)`

**Comment by sergioagg** [comment]
@juilianoj can you please  post a example of your full request to upload the file? I'm stuck trying to do the same.

**Comment by juilianoj** [comment]
@sergioagg Here's a full sample script for you. This listens for a message of 'testslackfileupload' followed by the name of the file you want to send to slack.  You can obviously set the file name within the script rather than passing it in through the message if you want.

```
# Description:
#   contains listener that will upload file to slack
#
# Commands:
#   hubot testslackfileupload <filename> - uploads file to slack with the filename passed in
#
# Author:
#   juilianoj

module.exports = (robot) ->	
	robot.respond /testslackfileupload (.*)/i, (res) ->
		filename = res.match[1]

		opts = {
			content: 'the content of your file'
			title: 'Your Test File Title As Displayed In Slack'
			channels: res.message.room
		}
		robot.adapter.client.web.files.upload(filename, opts)
```

The result looks like this, and when you download the file it would have the file name you passed in:

![image](https://user-images.githubusercontent.com/5711009/50719067-a69f3c80-105c-11e9-82d9-457f06efed3b.png)

**Comment by sergioagg** [comment]
@juilianoj awesome! that's exactly what I was looking for, really appreciated.
