### ISSUE TITLE
i'm new to create Hubot,when i run  the Hubot "bin/hubot" using this command,''bin'' is not recognized as an internal or external command, operable program or batch file. error came like this can anyone give me a solution

### ISSUE THREAD

**Issue by nagarajganesan93** [slackapi/hubot-slack#446]
### Description

Describe your issue here.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
by the fact that you mentioned batch files, it sounds like you are running on windows. i suggest you take a look at the [hubot documentation for deploying to windows](https://hubot.github.com/docs/deploying/windows/). at first glance, it sounds like you might just be using the wrong slashes (`./bin/hubot` -> `.\bin\hubot`).

**Comment by aoberoi** [comment]
closing, but if this continues to be a problem, feel free to comment and we can reopen.

**Comment by nagarajganesan93** [comment]
Hi,

Thank you for your valuable commands,still i'm facing issue.

i did the following steps:

step 1:npm install -g yo generator-hubot
step2: mkdir myhubot cd my hubot
step3: yo hubot
step4: bin\hubot

if i am using .\bin\hubot  i'll get the following error :"The system cannot
find the path specified."

pls send a demo of simple hubot run

Thanks in advance.

*Thanks,*

*With Best Regards*
*Nagaraj G*
*Mobile:+91 96776-75209*

**Comment by aoberoi** [comment]
i don't have a windows machine available right now to test on, but if you use `.\bin\hubot.cmd`, will that work? the error is saying the file doesn't exist, so you should check the contents of the `bin` directory to see what is there and what might be missing. just, `cd bin`, then `dir` to see what is inside that directory.

**Comment by aoberoi** [comment]
i haven't heard back, so i'll assume this issue is resolved.

**Comment by mvsuhas** [comment]
I am getting the below error 
When i run ".\bin\hubot" on windows CLI. Do i need to set any path for MySQL?

_up to date in 0.92s
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file._

**Comment by aoberoi** [comment]
@mvsuhas hubot and the hubot-slack adapter do not have any dependency on MySQL. if you are using another package to store hubot data in MySQL, i think you'll find more useful help from knowledgeable people who build that package.

**Comment by RebelF** [comment]
"The system cannot find the path specified."  error solution :

modify the file of bin/bubot.cmd 
change 
node_modules\.bin\hubot.cmd --name "myhubot" %* 
to 
..\node_modules\.bin\hubot.cmd --name "myhubot" %* 

save it and try again.

**Comment by abhigupta1990** [comment]
It started giving a new error now-
coffee:10:5: error: Can't reference 'this' before calling super in derived class
 constructors
    @data =
