### ISSUE TITLE
How to capture Hubot slack logs

### ISSUE THREAD

**Issue by ananthaa-advisory** [slackapi/hubot-slack#449]
### Description

I would like to capture Hubot-Slack logs, is  it possible

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

[demouser@nodea hubot]$ grep jerry jarvis.log
[Mon Nov 13 2017 03:09:58 GMT-0700 (MST)] INFO UUID1146 - jerry asked me - @jarvis ack down alerts on node1
[Mon Nov 13 2017 03:09:58 GMT-0700 (MST)] INFO UUID1146 - responded to jerry - Want me to accept unhandled alerts on Icinga? say - accept <alert_type>  ?
[Mon Nov 13 2017 03:10:31 GMT-0700 (MST)] INFO UUID1147 - jerry asked me - @jarvis accept down on node1
[Mon Nov 13 2017 03:10:31 GMT-0700 (MST)] INFO UUID1147 - responded to jerry - I am not really programmed for that !
[Mon Nov 13 2017 03:12:06 GMT-0700 (MST)] INFO UUID1148 - jerry asked me - jarvis @jarvis ack  httpd on nodeb
[Mon Nov 13 2017 03:12:06 GMT-0700 (MST)] INFO UUID1148 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:12:11 GMT-0700 (MST)] INFO UUID1148 - responded to jerry -
[Mon Nov 13 2017 03:13:30 GMT-0700 (MST)] INFO UUID1150 - jerry asked me - jarvis @jarvis accept httpd on nodeb
[Mon Nov 13 2017 03:13:30 GMT-0700 (MST)] INFO UUID1150 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:13:36 GMT-0700 (MST)] INFO UUID1150 - responded to jerry -
[Mon Nov 13 2017 03:49:48 GMT-0700 (MST)] INFO UUID1164 - jerry asked me - @jarvis accept httpd alerts on nodeb
[Mon Nov 13 2017 03:49:48 GMT-0700 (MST)] INFO UUID1164 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:49:54 GMT-0700 (MST)] INFO UUID1164 - responded to jerry -

#### Reproducible in:

hubot-slack version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

If the Hubot is not responding to a query, how to capture the text typed in by the user from the logs file. I am sure there is a way .

#### Actual result:

I am grepping the log files based on a INFO UUID*, which shows where the hubot fails to respond to user query. but it is not a complete result. I am only getting half of the text queries of the complete report.  Lets say, if we have 100 text queries, from my Perl command. I am able to capture only 50 queries as failed and missing the rest of the text queries. Is there a way to capture all the text queries which are failing.

Command that I use:

Output:
[demouser@nodea hubot]$ perl -nle ' if(/UUID\w+/){ if(++$count{$&}>2){ undef$line{$&}}else{ $line{$&}=$_}}END{print for values%line}' < hubot_jarvis.log | grep jerry
[Mon Nov 13 2017 03:09:58 GMT-0700 (MST)] INFO UUID1146 - responded to jerry - Want me to accept unhandled alerts on Icinga? say - accept <alert_type> ?
[Mon Nov 13 2017 03:10:31 GMT-0700 (MST)] INFO UUID1147 - responded to jerry - I am not really programmed for that !

Total text queries which were executed by user Jerry in Hubot is : 5
Total text queries failed by user in Hubot is :5

Below are the  text queries which are failed and Hubot fails to respond:

[demouser@nodea hubot]$ grep jerry jarvis.log
[Mon Nov 13 2017 03:09:58 GMT-0700 (MST)] INFO UUID1146 - jerry asked me - @jarvis ack down alerts on node1
[Mon Nov 13 2017 03:09:58 GMT-0700 (MST)] INFO UUID1146 - responded to jerry - Want me to accept unhandled alerts on Icinga? say - accept <alert_type>  ?
[Mon Nov 13 2017 03:10:31 GMT-0700 (MST)] INFO UUID1147 - jerry asked me - @jarvis accept down on node1
[Mon Nov 13 2017 03:10:31 GMT-0700 (MST)] INFO UUID1147 - responded to jerry - I am not really programmed for that !
[Mon Nov 13 2017 03:12:06 GMT-0700 (MST)] INFO UUID1148 - jerry asked me - jarvis @jarvis ack  httpd on nodeb
[Mon Nov 13 2017 03:12:06 GMT-0700 (MST)] INFO UUID1148 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:12:11 GMT-0700 (MST)] INFO UUID1148 - responded to jerry -
[Mon Nov 13 2017 03:13:30 GMT-0700 (MST)] INFO UUID1150 - jerry asked me - jarvis @jarvis accept httpd on nodeb
[Mon Nov 13 2017 03:13:30 GMT-0700 (MST)] INFO UUID1150 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:13:36 GMT-0700 (MST)] INFO UUID1150 - responded to jerry -
[Mon Nov 13 2017 03:49:48 GMT-0700 (MST)] INFO UUID1164 - jerry asked me - @jarvis accept httpd alerts on nodeb
[Mon Nov 13 2017 03:49:48 GMT-0700 (MST)] INFO UUID1164 - responded to jerry - Accepting httpd alert on nodeb ...
[Mon Nov 13 2017 03:49:54 GMT-0700 (MST)] INFO UUID1164 - responded to jerry -

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
hi @ananthaa-advisory, interesting use case. thanks for providing so much information.

if you want more information in the logs, you can adjust the log level for the robot instance to include 'debug' messages (in https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee#L186 you can see a logging statement that uses this level).

you can change the log level by setting the environment variable: `HUBOT_LOG_LEVEL=debug`.

**Comment by aoberoi** [comment]
Closing because I hope this answers your question, but feel free to keep replying if you have further questions.
