### ISSUE TITLE
Add support for `rtm.connect`, backfilling team info

### ISSUE THREAD

**Issue by Roach** [slackapi/hubot-slack#453]
### Description
Many enterprise users aren't able to call `rtm.start` due to team size and other constraints. 

- we need to add support for `rtm.connect`, which loads the websocket, but doesn't load the team data.

  - The downside of this is that much of Hubot's logic assumes that the team data is populated when it receives events, iterating through the user and channel lists, for example. We'll need to come up with an option to backfill that information after the websocket connection is made.

- We'll also need to call `bots.info` to get the bot's ID on load, so it can filter messages from itself

@lornajane has started this work by adding a check to see if the user list is populated before iterating through it in #452

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] enhancement (feature request)
- [x] discussion

**Comment by aoberoi** [comment]
@Roach i think this is a dup of #385 because the effect of removing the dependency on `@rtm.dataStore` would make `rtm.connect` supported. should we instead use this issue to capture the idea of using `rtm.connect` as the default?

**Comment by aoberoi** [comment]
also, removing `Priority–High` label. i'm trying to push away from using labels for prioritization and instead use Milestones (and potentially GitHub's Projects if needed).
