### ISSUE TITLE
change robot.react to robot.hearReaction

### ISSUE THREAD

**Issue by aoberoi** [slackapi/hubot-slack#455]
### Description

i propose that we change the method name from `react()` to `hearReaction()` in the next major version of this adapter. why? because i think semantically it makes more sense to think of the robot as hearing a reaction in a room, rather than the robot reacting (which it doesn't do unless you write code for it to do).

i don't think this issue is urgent, but it is a semver:major change. we could possibly get it out in a semver:minor change with a deprecation warning logged if the old method is used.

@mbland as the original author of this code, i'm hoping to get your input on this idea.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by mbland** [comment]
`hearReaction()` sounds good to me, or maybe `onReaction()`. I called it `react()` to keep with the style of other relatively terse method names, but agree a longer name would make things a little more obvious.
