### ISSUE TITLE
hubot in slack is active but looks offline

### ISSUE THREAD

**Issue by m-bharathkrishna** [slackapi/hubot-slack#457]
hubot in slack is active but looks offline. All of a sudden it started to appear offline but it responds to quereis and is functional. Not sure what got changed. I don't have any logs to share. Did any one else face this?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:

node version: v5.12.0

OS version(s): Ubuntu

#### Steps to reproduce:

1. Start the hubot along with SLACK TOKEN and Webhook using slack adapter

#### Expected result:

What you expected to happen: Hubot to appear online and active

#### Actual result:

What actually happened: Hubot is active but doesn't appear online

**Comment by aoberoi** [comment]
its possible that there was a momentary disconnection followed by a reconnection. is this still occurring? is it reproducible?

**Comment by m-bharathkrishna** [comment]
I never knew the root cause, it worked after couple of days.
