### ISSUE TITLE
Slack-hubot connection issue!

### ISSUE THREAD

**Issue by hrish32** [slackapi/hubot-slack#458]
Hello,
I have written this simple code in notepad++.
module.exports = (robot) ->
	console.log(robot)
	robot.respond /ping/i, (msg) ->
		msg.reply "pong"
It works well locally. But when I am trying to connect to the slack adapter, it throws error saying:
ERROR error listen EACCES 0.0.0.0:8080
How can I resolve this issue?

Thanks.

**Comment by aoberoi** [comment]
@hrish32 this error is a result of configuration on your machine. this can happen if that port is being used by another process, or if your user account does not have permission to listen to a TCP port.

i hope you aren't still stuck on this, but this repo isn't the best place to find help for this issue. it sounds like you are on windows, so you may want to search stackoverflow for windows users that have this error on node. the `hubot-slack` adapter does not try to listen to any ports.
