### ISSUE TITLE
Hubot 3.x compatibiltiy

### ISSUE THREAD

**Issue by aoberoi** [slackapi/hubot-slack#460]
### Description

This issue is to track information relevant to compatibility of this adapter with hubot@3.x. As of now, the `latest` tag on npm still points to 2.19.0, so we consider 3.x unstable but available for ourselves to start testing against.

We've received one report of an issue connecting to Slack using hubot@3.0.1. We aren't sure this is related to the version of hubot, but its something we can try to reproduce. In a clean hubot with no `external-scripts.json` and nothing in `scripts/`, the following errors were observed:

```
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
error: Response not OK: not_authed
error: Disconnecting because not_authed is not recoverable
error: Error: not_authed 
```

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ArcticSnowman** [comment]
With hubot 3.0.1 release for over a year... is not time to update ?

**Comment by aoberoi** [comment]
AFAIK 3.x isn't ready for prime time. A quick `npm info` reveals the following:

```
dist-tags:
beta: 2.8.3-beta  latest: 2.19.0    next: 3.0.1 
```

2.19.0 is the latest release and the default when you `npm install hubot`. the yeoman generator's (`generator-hubot`) is also in the same boat (latest release is 0.4.0 which references the latest hubot, `@next` release references `@next` hubot).

For now, only people that intentionally install with `npm install hubot@next` will get version 3. I haven't seen any plans to mark that version as the stable `latest`.

**Comment by ArcticSnowman** [comment]
Trying to remember why I needed to update hubot to 3.x in my bot...   however the latest addition of the peerDependencies to hubot 2.0.0. does break my builds.. and reverting to hubot 2.* break the bot..

**Comment by ArcticSnowman** [comment]
OK that's a issue with having 'coffeescript' over 'coffee-script' installed...

**Comment by ArcticSnowman** [comment]
it did.... will see how that runs...

**Comment by aoberoi** [comment]
@ArcticSnowman since this project depends on `coffeescript`, wouldn't depending on `coffee-script` due to other add-ons once again create a mixed project? I thought that's what you were saying caused the issues.

**Comment by ArcticSnowman** [comment]
I was installing `coffescript` globally and that seem to be the cause..  ..   and when I install hubot-slack... there is no reference to coffeescript ....

```
hubot-slack@4.5.3 node_modules/hubot-slack
├── bluebird@3.5.1
├── lodash@3.10.1
└── @slack/client@3.16.1-sec (inherits@2.0.3, eventemitter3@1.2.0, url-join@0.0.1, async@1.5.2, pkginfo@0.4.1, retry@0.9.0, ws@1.1.5, https-proxy-agent@1.0.0, request@2.87.0, lodash@4.17.10, winston@2.4.3)

```

**Comment by mistydemeo** [comment]
Has there been any progress on this? My team has been using Hubot 3 in production for a year, and we're currently blocked on upgrading to the latest `@slack/client` and `hubot-slack`.

**Comment by aoberoi** [comment]
@mistydemeo are you encountering the same `not_authed` error in the description, a package dep conflict, or something entirely new that isn't working?

**Comment by mistydemeo** [comment]
@aoberoi It's the `not_authed` error; my report is the one that triggered this issue being opened.

**Comment by aoberoi** [comment]
sorry, i lost track! thanks for reminding me.

**Comment by aoberoi** [comment]
To answer your question, no, we haven't invested any time into fixing the `not_authed` error nor understanding Hubot 3.x compatibility on the whole. I'd be willing to review and merge any PRs that address either, as long as they don't introduce any backwards-incompatible changes.

If you haven't tried reproducing the issue since the original report, I'd suggest trying again. So much of this project has be retouched or rewritten since then, that it might not be around any more. If you're still able to reproduce it on v4.5.3, that's also a good data point to have.

My gut feeling tells me that `not_authed` is related to the wrong or otherwise incompatible token being used, but I believe we double-checked that already. Might be worth one more check.

If you're available to chat in the Bot Developers Hangout (dev4slack), I'd be happy to get some data about the team ID, app ID, timestamp of your attempt to connect, etc; and see what i can learn from our internal logs about the reason for the error.

**Comment by mistydemeo** [comment]
> If you haven't tried reproducing the issue since the original report, I'd suggest trying again. So much of this project has be retouched or rewritten since then, that it might not be around any more. If you're still able to reproduce it on v4.5.3, that's also a good data point to have.

I'll give this a try soon. If I can still repro, I'll ping you in dev4slack and let you know the team ID/etc.

> My gut feeling tells me that not_authed is related to the wrong or otherwise incompatible token being used, but I believe we double-checked that already. Might be worth one more check.

This is the same token that we're using today with `@slack/client` 3.9.0, so I doubt that's the problem. 😄

**Comment by mistydemeo** [comment]
I tested this last night; as I expected, we saw the same behaviour as before using `@slack/client` 3.1.6-sec and the latest hubot-slack.

Just as an FYI, as of version 3.1.0, Hubot 3 is now the stable series.

**Comment by aoberoi** [comment]
@mistydemeo thanks for the heads up! the `generator-hubot` package is still at 0.4.0, which scaffolds a v2 hubot project. if the intention of the Hubot team is to move to v3 stable, they might want to consider bumping that dist-tag too.

**Comment by stephenyeargin** [comment]
`generator-hubot` finally shipped with the new scaffold.

https://github.com/hubotio/generator-hubot/releases/tag/v1.1.0

**Comment by aoberoi** [comment]
yay! thanks for the update.

on our end, @mistydemeo and i are in the process of debugging exactly what issues they are running into, but at this time we don't have any reason to believe its due to an incompatibility with `hubot@3`.

if anyone else has any good or bad experiences using v3, it would be nice to know here 😄

**Comment by ElectricWarr** [comment]
IANA[node developer], but I've updated my bot to use [this fork](https://github.com/ElectricWarr/hubot-slack) and everything so far seems to work using `"hubot": "^3.1.0"`.

If anyone wants to try this, in my `package.json` I just have `"hubot-slack": "electricwarr/hubot-slack"`, and it just grabs the repo like a normal module :)

**Comment by ElectricWarr** [comment]
IANA[node developer], but I've updated my bot to use this fork and everything so far seems to work using "hubot": "^3.1.0".

If anyone wants to try this, in my package.json I just have "hubot-slack": "electricwarr/hubot-slack", and it grabs the repo like a normal module :)

**Comment by lukaszlenart** [comment]
I have used `"hubot-slack": "electricwarr/hubot-slack"` and it works, thanks a lot!

**Comment by ElectricWarr** [comment]
@lukaszlenart no problem!

@aoberoi I'm sure I'll simply return to using `hubot-slack` proper as soon as that PR is approved & merged, perhaps best if I leave a message on the fork repo explaining that it won't be maintained in future. Thanks!

**Comment by aoberoi** [comment]
closed in #525

**Comment by lukaszlenart** [comment]
When can we expect a new version?

**Comment by aoberoi** [comment]
@lukaszlenart we just released a new version today, which includes hubot 3.x compatibility. are you having any issues with v4.5.5?

**Comment by lukaszlenart** [comment]
Nope, `npm install hubot-slack --save` just still installs 4.5.4, I will try again ;-)

**Comment by lukaszlenart** [comment]
Now it works, thanks a lot!
