### ISSUE TITLE
Wrong user being pinged when sending trigger msg through Slack Web API

### ISSUE THREAD

**Issue by MrLotU** [slackapi/hubot-slack#494]
### Description

Bot user gets pinged when a hubot command with `.reply()` gets triggered by a message that's created through the Slack Web API

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.4.0

node version: 10.4.0

OS version(s): MacOS 10.13.5

#### Steps to reproduce:

1. Create Hubot project
2. Create a command that uses `.reply()`
3. Execute the command using the [API tester](https://api.slack.com/methods/chat.postMessage/test) (Set as_user to true)

#### Expected result:

Message gets posted as user & reply mention is to the user

#### Actual result:

Message gets posted as user but reply mention is to the Slack API Tester

#### Attachments:

As seen in the image, instead of the user executing the command, the ID of the Slack API Tester app is pinged.

<img width="162" alt="screen shot 2018-06-12 at 13 04 20" src="https://user-images.githubusercontent.com/18392003/41286833-23ca8534-6e41-11e8-8f77-017961dcda76.png">

**Comment by MrLotU** [comment]
PR implementing fix: #495

**Comment by aoberoi** [comment]
Thanks for sending a fix. I haven’t looked at this issue in detail yet, but I’d like to clarify something. The latest version of this package is 4.5.0, so how can you be using 6.1.0?

**Comment by MrLotU** [comment]
Excuses, confused 2 commands, I'm on 4.5.0

**Comment by aoberoi** [comment]
@MrLotU would you be able to update to the latest version (4.5.0) and try again? there was a significant refactor of the construction of user objects which i believe should solve this issue. one caveat: i'm not 100% sure how messages posted using the API Tester (tester tokens) will be interpreted differently than messages from real users, so if possible, please test with a message posted from a real user. The tester token use case is not realistic for this project's goals.

**Comment by MrLotU** [comment]
Hi, sorry for the long wait. We've changed our setup on our end so we're not running in to this anymore.
