### ISSUE TITLE
hubot http endpoint

### ISSUE THREAD

**Issue by rbuezotordesillas** [slackapi/hubot-slack#514]
Does anyone know or understand how slack configures the communication with hubot? Does slack post to hubot http endpoint? 

What part of the code is this defined in? 

Thank you.

**Comment by aoberoi** [comment]
Hi, @rbuezotordesillas. Using this adapter, Hubot will connect to Slack using the [Real Time Messaging API](https://api.slack.com/rtm) and send messages using the [Web API](https://api.slack.com/web). The code for these is generally in `src/client.coffee`.

RTM is used by Hubot to receive incoming events (including messages). The code for event handling can be seen starting with the event handlers attached here: https://github.com/slackapi/hubot-slack/blob/b45cb8820ed088175853263aac7ac6ce749f393d/src/client.coffee#L49-L55.

The Web API is used by Hubot to send outgoing messages. That code is within the `SlackClient#send()` method: https://github.com/slackapi/hubot-slack/blob/b45cb8820ed088175853263aac7ac6ce749f393d/src/client.coffee#L160-L184.
