### ISSUE TITLE
Scripts triggered by SlackBot's /remind no longer working

### ISSUE THREAD

**Issue by Eibwen** [slackapi/hubot-slack#519]
### Description

In our slack, we had a trigger we wanted every day at a certain time, so used slack's `/remind #channel every day at 11am @hubot runScript` which worked great until Monday July 30th.  (We suspect Slack changed something on their end about how SlackBot is represented in its `user` object, and hubot-slack doesn't support some part of that)

Now it seems produce an error when that remind trigger runs:
`ERROR Incoming RTM message dropped due to error fetching info for a property: bot_not_found.`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: hubot-slack@4.5.3

node version: node 8.9.4 (npm 6.1.0)

OS version(s): CentOS Linux release 7.3.1611 (Core) 

#### Steps to reproduce:

1. Have a `robot.hear` command, say triggered on the text `command`, that does anything
2. Have hubot in a Slack channel, say called `#placeholder`
3. Enter the command `/remind #placeholder in 1 minute hubot command`
4. Wait 1 minute, in the channel you should see `slackbot [12:01 PM] Reminder: @hubot ping.`

#### Expected result:

The command result to occur

#### Actual result:

Nothing in the chat, error logged: `ERROR Incoming RTM message dropped due to error fetching info for a property: bot_not_found.`, from this line of code: https://github.com/slackapi/hubot-slack/blob/master/src/client.coffee#L364

#### Attachments:

N/A

**Comment by Eibwen** [comment]
Debugging level logs:

```
// when I as a user say a command (in this case @bot ping)
[Wed Aug 01 2018 16:53:19 GMT-0400 (Eastern Daylight Time)] DEBUG Received text message in channel: CC19PCCAH, from: UBEECPAH4 (human)
[Wed Aug 01 2018 16:53:19 GMT-0400 (Eastern Daylight Time)] DEBUG Message '@bot ping' matched regex //^\s*[@]?bot[:,]?\s*(?:(ping|hello)$)/i/; listener.options = { id: null }
[Wed Aug 01 2018 16:53:19 GMT-0400 (Eastern Daylight Time)] DEBUG Executing listener callback for Message '@bot ping'
[Wed Aug 01 2018 16:53:19 GMT-0400 (Eastern Daylight Time)] DEBUG SlackClient#send() room: CC19PDDAH, message: Pong

// When a reminder fires with just `ping.`, NOT `@bot ping` (so any remind text causes this error it seems)
error: Response not OK:  bot_not_found
[Wed Aug 01 2018 16:54:10 GMT-0400 (Eastern Daylight Time)] ERROR Incoming RTM message dropped due to error fetching info for a property: bot_not_found.

// When a reminder fires with `@bot ping.`
error: Response not OK:  bot_not_found
[Wed Aug 01 2018 16:54:29 GMT-0400 (Eastern Daylight Time)] ERROR Incoming RTM message dropped due to error fetching info for a property: bot_not_found.
```

**Comment by Eibwen** [comment]
Apparently slackbot is returned as "B01" everywhere now, and returns "bot_not_found" on `bots.info`

https://github.com/whywaita/slack-aggregator/commit/06b37f58c7b389222b90367374c5b2a309327ce5

**Comment by aoberoi** [comment]
@Eibwen thanks for reporting this. its obvious that we overlooked the special cases around slackbot, and surely this is a bug.

PS. using slackbot as a poor man's cronjob? genius!
