### ISSUE TITLE
About support for unfurling all links posted by bot

### ISSUE THREAD

**Issue by kevinnio** [slackapi/hubot-slack#531]
### Description

From the official [Slack API documentation on classic unfurling](https://api.slack.com/docs/message-link-unfurling#classic_unfurling):

>By default we unfurl all links in any messages posted by users. For messages posted via incoming webhooks, the chat.postMessage API method or chat.postEphemeral, we will unfurl links to media, but not other links.  
  
>If you'd like to override these defaults on a per-message basis you can pass unfurl_links or unfurl_media while posting that message. unfurl_links applies to text-based content, unfurl_media applies to media based content. These flags are mutually exclusive, the unfurl_links flag has no effect on media content.

I want my hubot to post links to tweets in a Slack channel. Problem is these links won't unfurl because tweets are not considered media. Solving this issue is easy: just send the `unfurl_links` flag in the request to the `chat.postMessage` endpoint, but looks like currently there's no way to do that in the adapter.

Is there any known workaround for this or do we need to have this included as a feature in a PR? If I add this feature myself, would you guys be willing to review it? You have some olds PRs related to this, that's why I'm asking.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
hi @kevinnio, i think the following code should work:

```coffeescript

module.exports = (robot) ->
  robot.hear /thanks/i, (res) ->
    res.send { text: "Here's a fun tweet: https://twitter.com/photographerjon/status/1046174097762332672", unfurl_links: true }
```

**Comment by kevinnio** [comment]
To anyone that might be wondering, that indeed worked.
