### ISSUE TITLE
hubot怎么与slack通

### ISSUE THREAD

**Issue by chenjiahuan** [slackapi/hubot-slack#539]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.
新手 因为前辈部署了hubot 和slack相同，现在hubot的服务器搬了地方，hubot连不上了，需要改什么配置吗
#### Reproducible in:

hubot-slack version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by iamam34** [comment]
(according to Google Translate)

Issue title: 
> How does hubot communicate with slack

Description:
> Novice Because the predecessor deployed the same hubot and slack, now the hubot server has moved to the place, the hubot can't connect, what configuration needs to be changed?

**Comment by seratch** [comment]
Could you share a bit more details of your issue (e.g., your Hubot scripts without confidential parts, package.json, etc)? Also, if you give those in English, it would be appreciated.
