### ISSUE TITLE
how to no  @hubot ,bot can response in channel ?

### ISSUE THREAD

**Issue by sssss31302** [slackapi/hubot-slack#555]
me:@hubot help
hubot:$%^$^
 |
 |
 ˇ
me:help
hubot:$%^$^

 
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by sinisterstuf** [comment]
Use `robot.respond` when you want the robot to respond directly to messages addressed to it, as in your `me:@hubot help` example and use `robot.hear` for any messages said in channel, as in your `me:help` example.

The following code would get the your above example working as-is:

```coffeescript
module.exports = (robot) ->
  robot.hear /help/, (res) ->
    res.send "$%^$^"
```

The example code is based on the examples from the [hearing and responding section of the Hubot basic scripting documentation](https://hubot.github.com/docs/scripting/#hearing-and-responding).

This is a general Hubot scripting question, not specific to Slack, so I propose closing this issue.

**Comment by seratch** [comment]
Thanks @sinisterstuf for responding here. I also think we can safely close this issue now.
@sssss31302 Please feel free to write in or reopen if you have something further to ask/discuss here.
