### ISSUE TITLE
Increase users.list page size (or make it configurable)

### ISSUE THREAD

**Issue by iancward** [slackapi/hubot-slack#557]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Enhancement
When the service fires up, it attempts to retrieve the entire list of users from Slack. In large workspaces, that can take a very long time, often slowing the bot down in the process.

Currently, this code hard-codes the page size limit to `100` (see [code](https://github.com/slackapi/hubot-slack/blob/dc7f2a815a1210a0253291959d47172661b8eba8/src/client.coffee#L11)); however, the API documentation [recommends](https://api.slack.com/methods/users.list#pagination) `200` and the value can be up to `1000`.

Please increase the default to `200` and ideally also provide a way to make this configurable to the end-user.

**Comment by aoberoi** [comment]
Hi @iancward,

I see how `100` can quickly exhaust the API limits for a large team. I can't think of a reason for it to be quite that low. So, I'm happy to increase it quite a bit. The only issue with going too large is that the responses may timeout if Slack ends up processing the query too long. I don't think we should go quite up until the limit. How does `800` sound to you?

**Comment by iancward** [comment]
Maybe set it to `200` (the recommendation) and make it configurable with an environment variable?

**Comment by ahmeduddin1132** [comment]
@aoberoi  I have  been having the same issue for a while, but however after increasing the PAGESIZE value the bots works for fine for couple days then suddenly go offline for couple of hours  that makes our support system completely offline. we have almost around **8K users** in slack. 

what would be the best value for the **PAGESIZE** variable. i tried 400, 600, 800 and 1000 as well but encountered same problem.

current config value we are using is **1000**

**Comment by seratch** [comment]
If someone is interested in making a pull request on this, I'm happy to review and ship the change in forthcoming releases.

**Comment by kintarowins** [comment]
https://github.com/slackapi/hubot-slack/pull/612

**Comment by seratch** [comment]
Fixed by #612
