### ISSUE TITLE
Using hubot's slack token directly, the bot user is displayed differently?

### ISSUE THREAD

**Issue by Blackrobe** [slackapi/hubot-slack#564]
### Description

I created a Hubot for my personal use, and invited it to a Slack channel for tests.

The project design is: A hubot running with Slack adapter will be designed to recognize user commands, and then call a local third party HTTP API according to the command and pass parameters using GET method. The local third party app will then use hubot's own slack token to post back to the channel the hubot listens to.

The third party app is a python script which uses the same HUBOT_SLACK_TOKEN the coffeescript does, and by using python's `slackclient` package the python script uses the token to post messages in the same channel hubot listens to.

Please refer to the "Expected result" vs "Actual result" below.

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

hubot-slack version: latest
node version: latest
OS version(s): Debian 9

#### Expected result:

The message posted via Python script (which uses slackclient python package and hubot's slack token) has the same user picture and user name with actual hubot (picture: snake emoji, name: "Tanya Data").

#### Actual result:

User pictures and names between the actual hubot and python script-triggered bot is different (python-triggered has default bot picture instead of snake emoji and "bot" name instead of "Tanya Data").

See attachments below.

#### Attachments:

![image](https://user-images.githubusercontent.com/14886923/57130084-a0c72700-6dc2-11e9-8a4b-c7e8909faaa6.png)

Tanya Data was ran using bin/hubot --adapter slack, and the Bot user ran using python script that accesses the hubot's slack token.

**Comment by seratch** [comment]
I know this is a late response here (almost 1 year later...) but let me share some ideas anyways.

If your app is already migrated to the latest permission model, you can find [`chat:write.customize`](https://api.slack.com/scopes/chat:write.customize) permission. With this permission, you can customize the appearance of bot messages by specifying `username`, `icon_url`, and `icon_emoji`.

I hope this is helpful to you despite the delay.
