### ISSUE TITLE
No Token Provided

### ISSUE THREAD

**Issue by Awangatanggg** [slackapi/hubot-slack#570]
### Description

Im trying to deploy my hubot to my slack workspace, however im having some trouble setting the environment variables for the slack token.  I've gone through the installation as normal and created my hubot.  However when im attempting to deploy it to Slack with " .\bin\hubot -a slack " I get a " ERROR No token provided to Hubot ".  I've gone through the documentation on deploying Hubot to windows and i've set the environment variables in powershell using " [Environment]::SetEnvironmentVariable("HUBOT_SLACK_TOKEN", "xoxb-redacted", "Machine") so im not sure if there is something wrong with the way im trying to deploy to slack.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:

node version: 10.16

OS version(s): Windows

#### Steps to reproduce:

1. Installed Hubot normally
2. Set the HUBOT_SLACK_TOKEN env variable in powershell
3. Try to deploy to Slack

#### Expected result:

To have the bot deploy to my Slack workspace

#### Actual result:
No token provided error

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by clavin** [comment]
I have a hunch that the powershell command you used doesn't do exactly what you expect it to do.

#### Why not?

The .NET method [`Environment.SetEnvironmentVariable` with a `target` parameter](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8#System_Environment_SetEnvironmentVariable_System_String_System_String_System_EnvironmentVariableTarget_) you cited modifies the environment variables in different places depending on the `target` you supply. The one you supplied in your command was [`Machine`](https://docs.microsoft.com/en-us/dotnet/api/system.environmentvariabletarget?view=netframework-4.8#fields), which modifies the Windows registry to add/change the env variable. There's two issues with this:

1. Your command-line process (PowerShell) already loaded environment variables when it started up, so changing it at the source won't update the ones your CLI has *already* loaded. You'd need to reload them to get them to update.
2. There's not really a good reason to store your token in the system registry. It's recommended to store the token in the current process' environment variables (PowerShell's `$env`) instead.

#### What should I be doing then?

Set the env variable for the PowerShell session [using `$env`](https://stackoverflow.com/a/1422082):

```powershell
$env:HUBOT_SLACK_TOKEN = 'xoxb-myfavoritebot'; .\bin\hubot -a slack
```

This stores your token in the `HUBOT_SLACK_TOKEN` variable for as long as your PowerShell session is running (e.g. from when you open the shell until you close the shell). After that, the session's environment variables will be deleted. This means your token won't leak system-wide & that you don't need to refresh your session to get it to show up in your environment variables.

---

Another workaround is to use the [`dotenv` tool](https://github.com/motdotla/dotenv) to automatically load this variable from a `.env` file in your project--however make sure this `.env` file is **never uploaded** by adding it to your `.gitignore` and using other other appropriate guards.

**Comment by Awangatanggg** [comment]
Thank you it worked!
