### ISSUE TITLE
Sample code for Slack message menus and Hubot?

### ISSUE THREAD

**Issue by senattcsgit** [slackapi/hubot-slack#571]
Does anyone have or can share a hubot and slack message menu's integration code? 
my requirement is: whenever user choses an option from menu, how do i capture that selection in hubot?

I tried hubot-interactive-messages but receiving this error: 

Unable to load /home/xxxx/app/scripts/xxxxx: TypeError: robot.setOptionsHandler is not a function

here is my package.json
```json
{
  "name": "xxxxxx",
  "version": "0.0.0",
  "private": true,
  "author": "xxxxxxxxxx",
  "description": "xxxxxxxx",
  "dependencies": {
    "coffee-script": "^1.11.1",
    "hubot": "^3.3.2",
    "hubot-diagnostics": "^1.0.0",
    "hubot-help": "^1.0.1",
    "hubot-pugme": "^0.1.1",
    "hubot-rules": "^1.0.0",
    "hubot-slack": "^4.7.1",
    "hubot-interactive-messages": "^0.0.2"
  }
}
```

**Comment by BalasubramanyamEvani** [comment]
Hi @senattcsgit , this is a little late but hope it helps.

You can do the following in order to receive the selection from the menu in slack

```
// get hubot instance
// it responds with the same attachment for any input
// the attachment constains a selection menu, with two options
module.exports = (robot) => {
    robot.respond(/(.*)/i, (res) => {
        let menuAttachment = {
            text: "Menu option selectio",
            response_type: "in_channel",
            attachments: [
                {
                    text: "choose one of the following",
                    fallback: "fallback text",
                    color: "#00ff00",
                    callback_id: "menn_item_selection",
                    attachment_type: "default",
                    actions: [
                        {
                            name: "list of options",
                            text: "pick one",
                            type: "select",
                            options: [
                                {
                                    text: "option 1",
                                    value: "Option 1"
                                },
                                {
                                    text: "option 2",
                                    value: "Option 2"
                                }
                            ]
                        }
                    ]
                }
            ]
        };
        res.send(menuAttachment);
    });
    // hubot creates a http listener, by default at port 8080
    // if on localhost use service by "ngrok" to tunnel in order to get a public end point
    // now, whatever interactive option the user selects slack sends it back to this endpoint as a POST request
    // you can then read the request and continue
    robot.router.post('/hubot/listener', (req, res) => {
        console.log(req);
    });
};
```

Steps to do in the slack..

Go to https://api.slack.com/apps select your hubot_app and click on Add features and functionality, select interactive components, there will be a section where you will need to enter an endpoint which SLACK will use to send POST  requests with the user selection from the respective interactive message.

Hubot creates a http listener which I've used in the above code you can read more about this here https://github.com/hubotio/hubot/blob/master/docs/scripting.md

The above code is just a basic implementation, if you want security (which you should) add checks whether it's a valid request or not. check this https://api.slack.com/docs/verifying-requests-from-slack for better understanding

**Comment by seratch** [comment]
Hello @senattcsgit,

As @BalasubramanyamEvani mentioned, to receive incoming requests generated by user actions (e.g., clicking a button, selecting an item from a select menu in messages), you need to build a public endpoint to accept those requests from Slack API server. The app needs to be a web service, not a Hubot app that connects to Slack API over RTM (WebSocket) API. 

Unfortunately, there is no way to receive those user action events over WebSocket at this point. I hope this is helpful to you.

**Comment by raycharius** [comment]
An easier way of handling this would be to use a wrapper library. I just open sourced mine –  [slack-block-builder](https://github.com/raycharius/slack-block-builder).

Another good one is [jsx-slack](https://github.com/speee/jsx-slack) (if you prefer JSX syntax)
