### ISSUE TITLE
Enter/leave messages don't have timestamps

### ISSUE THREAD

**Issue by sinisterstuf** [slackapi/hubot-slack#575]
### Description

Marking this as question because I'm not sure it's a bug. I've noticed that the enter and leave events are missing a timestamp (I will talk about only enter events from here on because leave events behave the same).

Most things in the eventHandler return a timestamp from `event.ts` or `event.event_ts`. Enter events do not: ([source](https://github.com/slackapi/hubot-slack/blob/master/src/bot.coffee#L262-L266))

```coffeescript
    else if event.type is "member_joined_channel"
      # this event type always has a channel
      user.room = channel
      @robot.logger.debug "Received enter message for user: #{user.id}, joining: #{channel}"
      @receive new EnterMessage user
```

The only thing it passes to `@receive` is user, and you can see as much if you console.log what you get when using `robot.enter` as a script developer; you have user data and that's it.

My use case is: I'd like the robot to apply emoji reactions to the message for the enter event in Slack but that action [requires a timestamp and a channel](https://api.slack.com/methods/reactions.add#arguments). I can get the channel from room, kinda, but I don't have the message timestamp.

To be honest it's not clear to me whether that RTM event even contains a timestamp or not because the documentation for [member_joined_channel](https://api.slack.com/events/member_joined_channel) does not include a timestamp in the example even though the example in [the 2017 blog post introducing this event](https://api.slack.com/changelog/2017-05-rethinking-channel-entrance-and-exit-events-and-messages) _does_ include one. What's for sure is that the [message/channel_join](https://api.slack.com/events/message/channel_join) _did_ include a timestamp and probably its frequency would be sufficient for my use case but we moved away from using that in #513.

If the RTM event member_joined_channel does include a timestamp, this is perfect and I will create a pull request to try to propogate that timestamp to Hubot. How can I find that out?

If it does _not_ have one, then it is probably intentional and in that case, how can I work around the now-missing message/channel_join which has the timestamp I need?

Sorry for the wall of text 😅

### What type of issue is this?
- [x] question

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by sinisterstuf** [comment]
OK after a bit of experimentation and a message back and forth with Slack support I can confirm that member_joined_channel and member_left_channel both have timestamps, so I'm going to give a go at a pull request for this later.

Two impediments I can foresee:

1. I'll need some guidance on appropriate unit tests for this
2. I have no idea how I could actually reproduce this and prove that it works except for trying it out in production, how is this usually done?

**Comment by seratch** [comment]
I know this is a very slow response and I'm sorry that you haven't got any response when you posted here a few months ago. As you mentioned, there is no way to get `ts` for member_joined_channel` (and similar) events. If you're still interested in making a pull request for this, I'm happy to review and ship the change.

I've verified changing the following way works.

```coffee
    else if event.type is "member_joined_channel"
      # this event type always has a channel
      user.room = channel
      @robot.logger.debug "Received enter message for user: #{user.id}, joining: #{channel}"
      msg = new EnterMessage user
      msg.ts = event.ts
      @receive msg
```

On the script side, developers can access the value by `res.message.ts`.

```coffee
module.exports = (robot) ->
  robot.enter (res) ->
    robot.logger.info res.message.ts
```

Some may think that adding extra properties to `EnterMessage` class (it's a part of Hubot framework - [source code this adapter is compatible](https://github.com/hubotio/hubot/blob/v2.19.0/src/message.coffee#L42)) is not straight-forward. But I think it's okay to have those as long as it doesn't have conflicts with the names reserved by Hubot (specifically `user`, `room`, and `done` at this point).

**Comment by sinisterstuf** [comment]
Thanks for the advice @seratch I've gone and implemented your suggestion of

```coffeescript
msg = new EnterMessage user
msg.ts = event.ts
@receive msg
```

It works but I'm a bit envious of other event types where the timestamp can just be slapped onto the end of the arguments list to the constructor like `@receive new FooBar user, event.ts` but that's life 🤷‍♀️ on the other hand tests were much easier to write than I expected! 😄

> sorry that you haven't got any response when you posted here a few months ago

No problem, I opened this issue last year after a deep dive into the topic on my day off and hadn't had time to pursue it since then anyway. Thanks for the help and support!
