### ISSUE TITLE
Can hubot hear to a specific channel?

### ISSUE THREAD

**Issue by ShipraShalini** [slackapi/hubot-slack#579]
I am writing a Hubot script where I want Hubot to listen to a particular slack channel for a specific command. If the command comes from this channel, only then Hubot should respond to it. I want to implement this on a script level, so I do not want to whitelist or blacklist channels. I can achieve this using `robot.hear` and an `if` condition but I was wondering if there’s a better way to do this. I welcome your suggestions.

**Comment by seratch** [comment]
I know this is a late response here... but you can test if `res.message.rawMessage.channel` value matches.

```coffee
module.exports = (robot) ->
  robot.hear /test/i, (res) ->
    robot.logger.info res.message.rawMessage.channel
```

**Comment by seratch** [comment]
Let us close this issue due to inactivity. Please feel free to reopen the issue if it isn't resolved.
