### ISSUE TITLE
Add robot.enter and robot.leave support?

### ISSUE THREAD

**Issue by aendra-rininsland** [slackapi/hubot-slack#58]
Hi again!
I have a really basic script setup to post when users enter or leave rooms:

``` coffee
enterReplies = ["WELCOME TO THE THUNDERDROME", "WELCOME TO THE JUUUUUNGLLLEEEEE!"]

leaveReplies = [":crying_cat_face:", ":crying_cat_face: Nooooooooo! Anything but that!", "They're dropping like FLIES!"]

module.exports = (robot) ->
  robot.enter (msg) ->
    msg.send msg.random enterReplies

  robot.leave (msg) ->
    msg.send msg.random leaveReplies
```

...But I can't seem to get it to work (Just tested it).

My guess is that enter/leave messages aren't output via the Slack webhook? If not, it'd require a bit of work on the Slack side to make this happen (for which I'm no help, alas).

**Comment by Kenshinhu** [comment]
How to Tigger Enter or Leave?
I cant't work it on v3
