### ISSUE TITLE
Hubot can't respond to User Group mentions

### ISSUE THREAD

**Issue by danpalmer** [slackapi/hubot-slack#580]
### Description

User Groups allow multiple users to be @ mentioned in one go, or to build a sort of "dynamic dispatch" messaging system like `@on-call-responder` that can be set to different users based on a rota.

Hubot has a `respond` callback, which will trigger when Hubot is mentioned.

Currently, this callback is not triggered by a user-group mention when Hubot is in a user group.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.7.1 

node version: 7.10.1

OS version(s): Debian Jessie

#### Steps to reproduce:

1. Create a user group, e.g. `@test`
2. Put `@hubot` in the group `@test`
3. With the following script:

```js
module.exports = function(robot) {
  robot.respond(/test/i, function(res) {
    res.send("pong");
  });
}
```

4. Message `@test ping`

#### Expected result:

No reply from Hubot.

Messaging Hubot with `@hubot test ping` does however result in this, but is not using the user group.

#### Actual result:

A reply from Hubot of `pong`

**Comment by seratch** [comment]
I know this is a late response but let me share some ideas here.

`robot.respond` works only when a Hubot user is mentioned by a real user (not user group) in a message.

One possible solution for your use case would be including a mention to the user group in a message posted by a Hubot user regardless of the trigger (I mean not only robot.respond but robot.hear can be used for it).

Refer to the document for the details about supergroup mention if you're not familiar with it. https://api.slack.com/reference/surfaces/formatting#mentioning-groups

I hope this is helpful to you despite the delay.

**Comment by seratch** [comment]
Let us close this issue due to inactivity. Please feel free to reopen the issue if it isn't resolved.
