### ISSUE TITLE
99

### ISSUE THREAD

**Issue by vlkn79** [slackapi/hubot-slack#582]
### Description

Describe your issue here.

### What type of issue is this? (place an `` in one of the `[ ]`)
- [ ] bug
- [× ] enhancement (feature request)
- [ ×] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [× ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ×] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ×] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by stevengill** [comment]
Hey @vlkn79,

I think you forgot to fill out the issue template. Want to update this issue with the relevant details for your enhancement/question?

**Comment by vlkn79** [comment]
@stevengill thank you no problem
Sory
