### ISSUE TITLE
error: Response not OK:  not_allowed_token_type

### ISSUE THREAD

**Issue by EasyAsABC123** [slackapi/hubot-slack#584]
### Description

Running `HUBOT_SLACK_TOKEN=xoxb-[omitted] ./bin/hubot --adapter slack`
results in
```
rror: Response not OK:  not_allowed_token_type
info: Unable to rtm.start, attempting reconnect
warn: Reconnecting, on attempt 1
error: Response not OK:  not_allowed_token_type
info: Unable to rtm.start, attempting reconnect
warn: Reconnecting, on attempt 2
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

`error: Response not OK:  not_allowed_token_type`

#### Reproducible in:

hubot-slack version: 4.7.1

node version: v12.4.0

OS version(s): MacOS 10.15.3

#### Steps to reproduce:

1. yo hubot
2. add slack adapter
3. run with slack adapter putting in a token that doesn't have classic bot scope (deprecated)

#### Expected result:

It to connect to the workspace

#### Actual result:

fails to connect unsupported token, this works on my other app that has the classic token.

#### Attachments:

![Screen Shot 2020-02-13 at 2 14 17 PM](https://user-images.githubusercontent.com/1851104/74469794-530c3e80-4e6b-11ea-9d92-e16db840edaa.png)

**Comment by seratch** [comment]
>putting in a token that doesn't have classic bot scope (deprecated)

As you may be aware, RTM is no longer available for granular-permissions-enabled (= the default) apps. That's the reason you encountered this issue.

It's still possible to create a new classic app from [this URL](https://api.slack.com/apps?new_classic_app=1). Please refer to the document for details: https://api.slack.com/authentication/migration#classic

It would be appreciated if you could understand this. 🙇

**Comment by EasyAsABC123** [comment]
I’ll give it a go tomorrow thanks for clarifying the issue!

**Comment by relistan** [comment]
As of today it seems not possible to create apps with classic permissions. The above link works, but (despite what it says) it no longer creates a classic app.

**Comment by relistan** [comment]
This does work, using the link above. When assigning permissions you need to assign the Scope "bot" and it will warn you about it being deprecated. You also need to create a bot user from the "App Home" page on Slack before you can install to the workspace.

**Comment by tg90nor** [comment]
The docs should be updated to mention you need a classic app for this adapter to work.

**Comment by seratch** [comment]
@tg90nor Thanks for your feedback! I will feed your feedback to the team concerned. 🙇

**Comment by phanisowjanyavutukuri** [comment]
Hi,
Even I am getting the same error, Actually I wanted to migrate the hubot from legacy tokens to oauth tokens
Can anyone help in this

**Comment by seratch** [comment]
@phanisowjanyavutukuri 
https://github.com/slackapi/hubot-slack/issues/584#issuecomment-586020903 can be of help. In short, create a new "classic" app from [this URL](https://api.slack.com/apps?new_classic_app=1).

**Comment by phanisowjanyavutukuri** [comment]
@seratch I have created the classic app and installed the app in the workspace with the oauth scope permissions but unable getting the Response not OK: not_allowed_token_type error
Did I miss anything

**Comment by seratch** [comment]
@phanisowjanyavutukuri There are two ways to configure Hubot app for Slack. Both should work fine for you.

## Setup Hubot integration

* https://slack.dev/hubot-slack/
* https://my.slack.com/apps/A0F7XDU93-hubot

## Setup a Classic App

* Create a classic app from https://api.slack.com/apps?new_classic_app=1
* Go to **Features** > **OAuth & Permissions** > **Scopes**
  * Click "Add an OAuth Scope"
  * Search "bot" and choose it
* Go to **Features** > **App Home** 
  * Click "Add Legacy Bot User"
  * Input "Display Name" and "Default username"
  * Click "Add"
* Go to **Settings** > **Install App**
  * Click "Install App to Workspace**
  * Complete the OAuth flow

**Comment by seratch** [comment]
As my previous comment answered this question, let me close this issue now. Please feel free to reopen if you have something to ask/clarify here.

**Comment by lukaszlenart** [comment]
@seratch I tried follow your advice but

> Search "bot" and choose it

there is not such scope as _bot_ :\

![Screenshot 2020-04-29 at 16 06 02](https://user-images.githubusercontent.com/170103/80605440-5effa980-8a33-11ea-8234-778e0073ba6d.png)

**Comment by lukaszlenart** [comment]
Ok, my bad, used wrong link :)

**Comment by sam-brownlow** [comment]
> Ok, my bad, used wrong link :)

for anyone else who stumbles into this edge case, you need to use the following link when creating your app

https://api.slack.com/apps?new_classic_app=1

(if you close the "create classic app" popup and then later click the button "create app," you will no longer be creating a classic app)
