### ISSUE TITLE
robot.listen for `/me` message broken in hubot ^3, hubot-slack ^4 ?

### ISSUE THREAD

**Issue by benpbolton** [slackapi/hubot-slack#591]
### Description

`hubot-slack` v ^4 (with `hubot` ^3) seems to have no method for capturing `me_message` via a CatchAllMessage `robot.listen` handler. This functionality was present in hubot-slack ^3 via the same listener. Notably: hubot-slack ^4 seems to replace the CatchAllMessage listener to capture PresenceMessage instead?

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

hubot-slack version: ^4.7.1

node version: 12

OS version(s): all

#### Steps to reproduce:

1. Add a global listener for all messages, eg.
```
  robot.listen(
    (message) ->
      # No longer sees `/me` "action" meMessage from slack adapter
      robot.logger.info message
    (response) ->
      # Nothin' to see here, but empty functions aren't allowed, so:
      return response
  )
```

2. Send a `/me` message in slack eg. `/me testing hubot-slack adapter`
3. Note that the global listener is unable to see the `/me` message

#### Expected result:

I expected the above to catch meMessages like `hubot-slack` ^3 did eg.

```
[Mon Apr 06 2020 09:37:31 GMT-0600 (Mountain Daylight Time)] INFO CatchAllMessage {
  message: {
    type: 'message',
    subtype: 'me_message',
    text: 'testing hubot-slack adapter',
    user: User {
      _properties: [Object],
      _modelName: 'User',
      ...
```

#### Actual result:

The above listener catches SlackTextMessage, ReactionMessage, CatchAllMessage -> message: PresenceMessage, ... but... no /me messages 😥

In effect, it *seems* like hubot-slack 4 replaces the previous listener CatchAllMessage to only catch presence messages ¯\\_(ツ)_/¯ 

#### Attachments:

![hubot-slack-3-no](https://user-images.githubusercontent.com/7146063/78577092-cdfa3180-77ea-11ea-9538-0d71fe95e1be.jpg)

**Comment by seratch** [comment]
Although I will be releasing v4.8.0 tomorrow, I didn't have the bandwidth to include a fix for this issue in the release.
