### ISSUE TITLE
Hubot-slack sending message twice

### ISSUE THREAD

**Issue by aindurthi** [slackapi/hubot-slack#600]
Recently, I am trying to connect my bot which is developed using hubot framework with slack channels. I am trying to deploy it in ECS docker container.For first time deployment, the bot is working fine. For example, if I give the respective message to it is only responding with the expected message once. But after doing some code modifications and tried to redeploy into ECS container, it is responding with the same message twice. Can someone please help me on this.

**Comment by stevengill** [comment]
@aindurthi could you provide information about your environment? (OS, hubot-slack version, etc)

**Comment by aindurthi** [comment]
Hi @stevengill ,

We are running it in a 'alphine' container.The versions which I am using currently are:

"hubot": "^2.19.0"
"hubot-slack": "4.8.0"

**Comment by seratch** [comment]
>But after doing some code modifications and tried to redeploy into ECS container, it is responding with the same message twice. Can someone please help me on this.

The most probable cause is that you have multiple running instances (in other words, containers). The situation may arise due to misconfiguration or blue/green deployment (I myself haven't tried this yet though).

**Comment by aindurthi** [comment]
@seratch , you mean to say that multiple instance of hubot-slack connections got established. For example, we did first deployment in to ECS container and which worked fine(like expected output is display). For next deployments, that the first initialized hubot-adapter not went down and with the next deployments one more hubot-slack adapter started listening to commands from the bot.

**Comment by seratch** [comment]
@aindurthi That's just my guess but your understanding may be right.

**Comment by seratch** [comment]
Hi @aindurthi, do you need further help regarding this matter? Please allow me to close this issue after waiting for your response for a few weeks.
