### ISSUE TITLE
@slack/client@3.16.1-sec.2' is not in the npm registry. error while installing hubot-slack

### ISSUE THREAD

**Issue by Saticppro** [slackapi/hubot-slack#601]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.8,0

node version:12.13.1

OS version(s):

#### Steps to reproduce:

1.npm install --save hubot-slack
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:
Expected to install and save the hubot-slack module
What actually happened

#### Attachments:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@slack%2fclient - Not found
npm ERR! 404
npm ERR! 404  '@slack/client@3.16.1-sec.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'hubot-slack'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T10_02_54_967Z-debug.log

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
It seems the npm registry is having an issue on their end. https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by seratch** [comment]
The npm registry is now operating normally. Let me close this issue now.

>The incident has been resolved and we see no errors with installing packages anymore. Posted 1 hour ago. Aug 06, 2020 - 12:01 UTC
https://status.npmjs.org/incidents/cksjqc1w11v5
