### ISSUE TITLE
Slack Hubot adapter should use new API, not RTM

### ISSUE THREAD

**Issue by esteban20304** [slackapi/hubot-slack#611]
### Description

Currently the Slack Hubot adapter uses RTM, which requires a classic app. Per the schedule here: https://api.slack.com/changelog/future functionality for classic apps is getting deprecated over time and it is already affecting the types of things we can do with Hubot. It's forseeable that eventually new classic apps can't be created.

Please implement ability for Hubot to connect to Slack using the newer, non classic apps so that we can utilize modern functionality.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: Latest version

node version: any

OS version(s): any

#### Steps to reproduce:

1. Create non classic app
2. Attempt to get Hubot to connect.

#### Expected result:

Hubot is able to connect to Slack.

#### Actual result:

Hubot cannot connect to Slack.

**Comment by esteban20304** [comment]
Bump

Perhaps the Slack adapter just needs to use the new Bolt framework? https://slack.dev/bolt-js/tutorial/getting-started

**Comment by stevengill** [comment]
Hey @esteban20304 , 

At this time we don't have plans to update the hubot adapter to work with events-api instead of RTM. We instead encourage developers to [migrate to Bolt](https://slack.dev/bolt-js/tutorial/hubot-migration)

**Comment by esteban20304** [comment]
Got it, thanks. Will migrate to Bolt instead.

**Comment by yypptest** [comment]
@stevengill, Could you pls explain more details why there's no plan to update the RTM API with event API or Web API? Is it because of the technical issues or feature missing of the new APIs?  Thank you!
