### ISSUE TITLE
slack hubot can not  listen events

### ISSUE THREAD

**Issue by lonbaw** [slackapi/hubot-slack#613]
### Description

在本地bin/hubot 启动程序后输入信息，可以监听到用户输入的内容。在slack 客户端有时候监听不到用户输入的信息。高频偶发。高频间断性出现 ！！！如何从网络方面排查呢？？？？？？？
`
module.exports = function (robot) {
  robot.hear(/@oncall/i, async function (res) {    
    logger.info('检测到有新请求发过来,提问内容：',res.message.text);
  }
  );
}

`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hi @lonbaw,

Thanks for reaching out about Hubot-Slack! 👋🏻 

Our maintainers can speak English and Japanese, but we don't have a maintainer who can speak or read Chinese.

Can you describe your issue in English or Japanese? We'd like to help you!

**Comment by lonbaw** [comment]
I add https_proxy,the problem has been solved

**Comment by seratch** [comment]
@lonbaw I'm glad to know you've figured your issue out! Let me close this issue now.
