### ISSUE TITLE
When receiving a bot writing message using the User OAuth Token, the res.message.user has room property only

### ISSUE THREAD

**Issue by buzztaiki** [slackapi/hubot-slack#615]
### Description

When receiving a bot writing message using the User OAuth Token, the `res.message.user` has `room` property only.
I expect it is user object. Until hubot-slack 4.5.5, it is user object in this situation.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

hubot-slack version: 4.8.1

node version: 15.4.0

OS version(s): 
```
uname -a
Linux echo 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
```

#### Steps to reproduce:

1. Run following hubot script:

   ```
   module.exports = (robot) ->
     robot.hear /show me/i, (res) ->
       console.log(res.message.user)
       res.send JSON.stringify(res.message.user, null, 2)
   ```

2. Create slack app (not hobot)
   - User Token Scopes:
     - `chat:write`
3. Install slack app to my workspace.
4. Copy [OAuth Access Token] value.
5. Run following script

   ```
   const { WebClient } = require("@slack/client")
   
   const web = new WebClient(process.env.SLACK_USER_TOKEN)
   web.chat.postMessage({
     channel: process.env.SLACK_CHANNEL,
     text: "show me",
   })
   ```

#### Expected result:

I expect get a user object from `res.message.user`.

```
User {
  id: 'U2C95QECR',
  name: 'buzztaiki',
  real_name: 'Taiki Sugawara',
  slack: {
    ...
  }
}
```

#### Actual result:

`res.message.user` has room property only.

```
{ room: 'C2C91PE5T' }
```

**Comment by buzztaiki** [comment]
Is it correct patch?

```diff
diff --git a/src/client.coffee b/src/client.coffee
index 98e27ab..432f253 100644
--- a/src/client.coffee
+++ b/src/client.coffee
@@ -332,10 +332,10 @@ class SlackClient
     if @eventHandler
       # fetch full representations of the user, bot, and potentially the item_user.
       fetches = {}
-      if event.bot_id
-        fetches.bot = @fetchBotUser event.bot_id
-      else if event.user
+      if event.user
         fetches.user = @fetchUser event.user
+      else if event.bot_id
+        fetches.bot = @fetchBotUser event.bot_id
       if event.item_user
         fetches.item_user = @fetchUser event.item_user
```

**Comment by buzztaiki** [comment]
This patch has been worked in my environment and situation.

**Comment by seratch** [comment]
@buzztaiki Thanks for taking the time to report this. I've confirmed that the payload for messages posted using a user token includes `bot_id` and `bot_profile`. Therefore, as you pointed out, the current logic does not work with it.

```json
{
  "bot_id": "B111",
  "suppress_notification": false,
  "type": "message",
  "text": "thanks a lot",
  "user": "U111",
  "team": "T111",
  "bot_profile": {},
  "source_team": "T111",
  "user_team": "T111",
  "channel": "C111",
  "event_ts": "1609114401.001400",
  "ts": "1609114401.001400"
}
```
Regarding the fix, it looks great to me. If you don't mind, could you send a pull request?

**Comment by buzztaiki** [comment]
> could you send a pull request?

Sorry, I missed look at your comment. I will send PR.

**Comment by buzztaiki** [comment]
@seratch I've create PR #617
