### ISSUE TITLE
bot to start thread on its own message?

### ISSUE THREAD

**Issue by thorro** [slackapi/hubot-slack#622]
### Description

Is there a possibility that the bot would post a reply message in a channel and start a thread on that message it just posted?
Reasoning is some commands produce a lot of output and would like those to be posted as a thread, but not as direct response to user's message to avoid cluttering that user's "Threads". Example:

(user) !some_command

(bot) hi user, I just started some_command for you
   (thread) command finished, output follows...

All solutions I've found start a thread on (user)'s message.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hey @thorro, checking [this document page](https://slack.dev/hubot-slack/basic_usage#working-with-threads) should be helpful for you!

**Comment by thorro** [comment]
@seratch hi, I read that, but I can only get it to reply on the user's message in thread, not on the one bot posted.

**Comment by seratch** [comment]
Ah, I see. Your goal is to reply to the hubot user's own message by creating a new thread. In this case, you may need to use chat.postMessage API using WebClient: https://slack.dev/hubot-slack/basic_usage#using-the-slack-web-api

**Comment by thorro** [comment]
Thanks, will give it a go.

**Comment by seratch** [comment]
Let me close this issue now. If you find anything to discuss further, feel free to write in.
