### ISSUE TITLE
Is it possible to have Hubot listen in multiple channels but only respond in one channel?

### ISSUE THREAD

**Issue by magander3** [slackapi/hubot-slack#623]
Hi,
my Hubot is included in multiple channels and i would like send responses to just a few of them in some cases e.g robot listen for the below in all channels but should only provide a response when the hear string is found channel X.

```coffeescript
robot.hear /(license.*FAQ)/i, (res) ->
  str = "Consult the license section in \n- <https://123.com|Software FAQ>.\n"
  str += " \n"
  str += "Thank you\n"
  str += "Software Team\n"
  if !res.message.rawMessage.thread_ts?
   res.message.thread_ts = res.message.rawMessage.ts
   res.send str
```

Please advice how to do this.

thanks

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:4.8.1

node version: v10.23.1

OS version(s):CentOS Linux release 7.9.2009

#### Steps to reproduce:

1. N/A
2.
3.

**Comment by seratch** [comment]
Hi @magander3, thanks for asking this question!

I think there is no fancy way to realize this. I would recommend just checking `message.channel` to determine whether your bot user should respond to or not in listener code.

**Comment by magander3** [comment]
Hi @seratch , do you have any example of how to actually do this?

i have multiple things in the response e.g. res.message.channel.channelID and others.

thanks.
