### ISSUE TITLE
Get the last reply in a thread 

### ISSUE THREAD

**Issue by miltlima** [slackapi/hubot-slack#626]
### Description

Hello everyone,
I built a hubot a long time ago, but now I need to take the last answer in a thread and put it in a variable, but I have no idea how to do this in Hubot, I already did some research and I didn't find the answer, someone already needed it to do something similar?

Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:
v4.9.0

node version:
v16.2.0

OS version(s):
Debian GNU/Linux 10

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by stevengill** [comment]
Question, How do you know know a thread is complete? Do you want to respond to every message in the thread? Will there be like a emoji or some other means to indicate that your app should run? Are you going to do it time based?

**Comment by miltlima** [comment]
@stevengill hello @stevengill, I just want to reply to the last message, in this case it is a link, when the user clicks on a react emoji, the hubot will take the last sentence of the thread and play in a variable

**Comment by miltlima** [comment]
hello @stevengill, I just want to reply to the last message, in this case it is a link, when the user clicks on a react emoji, the hubot will take the last sentence of the thread and play in a variable

**Comment by seratch** [comment]
@miltlima How about doing like this? I haven't verified it actually works but doing similar should work for you.

```coffeescript
  # listen to all incoming messages
  robot.hear /.*/, (res) ->
    if res.message.thread_ts?
      # do something here
```

The above code example is a combination of examples in this document: https://slack.dev/hubot-slack/basic_usage Refer to the document for more information.

**Comment by miltlima** [comment]
Thanks @seratch for explanation !

I used a Slack API response function with an index for the 3rd thread message and solved

` const replies = await app.conversations.replies({
        channel: msg.message.item.channel,
        ts: msg.message.item.ts
      })

      const infoUrl = await getInfoFromUrl(replies.messages[2].text);`
