### ISSUE TITLE
@slack/client is no longer developed, and its dependency "ws" has a security vulnerability

### ISSUE THREAD

**Issue by CleanCut** [slackapi/hubot-slack#629]
### Description

[@slack/client](https://www.npmjs.com/package/@slack/client/v/5.0.2) is marked as "legacy", last had a release 2 years ago, and has a dependency, [`ws`](https://www.npmjs.com/package/ws), which has a [security vulnerability](https://github.com/advisories/GHSA-6fc8-4gx4-v693).  I don't expect that this will be fixed in `@slack/client` since they have been recommending for two years for people to use one or more of [@slack/web-api](https://www.npmjs.com/package/@slack/web-api), [@slack/rtm-api](https://www.npmjs.com/package/@slack/rtm-api), or [@slack/webhook](https://www.npmjs.com/package/@slack/webhook) instead.

I am not a node developer myself, but something I use uses `hubot-slack`, and we would like to keep up on patching security vulnerabilities. Does anyone know what this would take to switch from `@slack/client` to one or more of the suggested newer libraries? I would be willing to put some time into learning how to upgrade this if it would be helpful.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: `master` on 3 Sep 2021 and `4.9.0`

node version: N/A

OS version(s): N/A

#### Steps to reproduce:

N/A

#### Expected result:

N/A

#### Actual result:

N/A

#### Attachments:

N/A

**Comment by seratch** [comment]
Hi @CleanCut, thanks for flagging this!

Rergarding the specific vulnerability https://github.com/advisories/GHSA-6fc8-4gx4-v693, it does not affect this package and its underlying `@slack/client`. The security issue can arise only when you "ws" package for WebSocket servers. And, as far as I know, there are no critical security issues with old versions of "ws" as of today. 

With that being said, I agree that this package should be available also with newer versions of the Web API caller and WebSocket connection management layer. Although our team is not actively working on this package these days, we (perhaps, I) can improve this in future releases.

**Comment by CleanCut** [comment]
In that case, I can close our own vulnerability as not using the affected code. Thanks!
