### ISSUE TITLE
Hubot failing to set up with error: Response not OK:  method_deprecated

### ISSUE THREAD

**Issue by dwardu89** [slackapi/hubot-slack#636]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.9.0

node version: 14

OS version(s): centos 7 (Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type)

#### Steps to reproduce:

1. Create a slack bot following the instructions found on https://slack.dev/hubot-slack/ (including NOT upgrading permissions)
2. HUBOT_SLACK_TOKEN=xoxb-XXXXXX ./bin/hubot --adapter slack

#### Expected result:

slack bot expected to be set up 

#### Actual result:

```warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
error: Response not OK:  method_deprecated
info: Unable to rtm.start, attempting reconnect
warn: Reconnecting, on attempt 1
error: Response not OK:  method_deprecated
info: Unable to rtm.start, attempting reconnect
warn: Reconnecting, on attempt 2
error: Response not OK:  method_deprecated
info: Unable to rtm.start, attempting reconnect
warn: Reconnecting, on attempt 3
error: Response not OK:  method_deprecated
info: Unable to rtm.start, attempting reconnect
```

#### Attachments:

N/A

**Comment by danhigham** [comment]
@dwardu89 Hi Edward, I'm seeing this also, and I noticed you closed this issue without a resolution, did you figure it out?

**Comment by rayisbadat** [comment]
> @dwardu89 Hi Edward, I'm seeing this also, and I noticed you closed this issue without a resolution, did you figure it out?

I also ran into this today on my first try following the guide for the first time, so if anyone figured it out id be appreciated.

**Comment by danhigham** [comment]
@seratch Excellent! Thank so much.
