### ISSUE TITLE
After SlackClient#send(), I can not receive message sometimes

### ISSUE THREAD

**Issue by yihchu** [slackapi/hubot-slack#642]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I check the hubot logs, and sometimes it print 'DEBUG SlackClient#send() room: C03PGCYPT99, message: Hello World.', but i can not receive any message in slack.

#### Reproducible in:

hubot-slack version: ^4.10.0

node version: v14.15.3

OS version(s): cenos7.9

#### Steps to reproduce:

1. new a hubot
2. add it into a slack channel
3. modify 'example.coffee'
4. start hubot
5. send message in slack

#### Expected result:

receive reply

#### Actual result:

Can not receive reply sometimes.

#### Attachments:

logs:
```
[Fri Jul 15 2022 10:36:03 GMT+0800 (中国标准时间)] DEBUG Message 'hello' matched regex //hello/i/; listener.options = { id: null }
[Fri Jul 15 2022 10:36:03 GMT+0800 (中国标准时间)] DEBUG Executing listener callback for Message 'hello'
[Fri Jul 15 2022 10:36:03 GMT+0800 (中国标准时间)] DEBUG SlackClient#send() room: C03PGCYPT99, message: Hello World.
[Fri Jul 15 2022 10:36:09 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PLQLEJKV
[Fri Jul 15 2022 10:36:09 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 10:36:10 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PP9DE90U
[Fri Jul 15 2022 10:36:10 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PP9F9RS8
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: C03PGCYPT99, from: W9Z9MFWHG (human)
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG Message 'hello' matched regex //hello/i/; listener.options = { id: null }
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG Executing listener callback for Message 'hello'
[Fri Jul 15 2022 10:36:21 GMT+0800 (中国标准时间)] DEBUG SlackClient#send() room: C03PGCYPT99, message: Hello World.
```

screenshot:
<img width="563" alt="截屏2022-07-15 10 40 33" src="https://user-images.githubusercontent.com/11792362/179136300-a9e859f1-a238-4e50-bd7e-0fc8938f7d4b.png">

**Comment by seratch** [comment]
HI @yihchu, thanks for writing in. With given information, I am not sure what's happening to your Hubot app yet. Also, just in case, I tried to reproduce your situation on my end but I haven't managed to see the same. If anyone else has experienced something similar, sharing your thoughts would be appreciated.

**Comment by yihchu** [comment]
> HI @yihchu, thanks for writing in. With given information, I am not sure what's happening to your Hubot app yet. Also, just in case, I tried to reproduce your situation on my end but I haven't managed to see the same. If anyone else has experienced something similar, sharing your thoughts would be appreciated.

Thanks for reply. 

Now the situation is, After i start the hobot, it works well, but after some time(maybe 1-2 minutes, i can not give the exact time), the issue will happen.
And more time goes by(maybe another 2 minutes), #641 will happen, logs and screenshot is below. I can not figure out what happened.

```
[Fri Jul 15 2022 13:15:58 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: C03PGCYPT99, from: W9Z9MFWHG (human)
[Fri Jul 15 2022 13:16:04 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: C03PGCYPT99, from: W9Z9MFWHG (human)
[Fri Jul 15 2022 13:16:08 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: C03PGCYPT99, from: W9Z9MFWHG (human)
```
<img width="342" alt="截屏2022-07-15 13 17 46" src="https://user-images.githubusercontent.com/11792362/179155718-088b025c-fbee-4992-9b29-447a2e28b26c.png">

**Comment by yihchu** [comment]
And I have another question, that is if a hobot named judy has a command, like '/judy tell me a joke.'  And there is another hobot named karl, if karl said `/judy tell me a joke` in slack, does judy's command be triggered?  Does this command distinguish human or machine ?
