### ISSUE TITLE
DEBUG Received file_shared message from: undefined, file_id: F03PMLTMBNE

### ISSUE THREAD

**Issue by yihchu** [slackapi/hubot-slack#643]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Why the log `DEBUG Received file_shared message from: undefined, file_id: F03PMLTMBNE` appears time and time again. I'm sure I do not send any files.

#### Reproducible in:

hubot-slack version: ^4.10.0

node version: v14.15.3

OS version(s): cenos7.9

#### Steps to reproduce:

just start hubot, make sure the bot is in a slack channel.
And send some message, and wait.
5 - 10 minutes later, the log will appears frequently.

#### Expected result:

No wired logs appear.

#### Actual result:

```
[Fri Jul 15 2022 15:55:37 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PMLTMBNE
[Fri Jul 15 2022 15:55:37 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 15:55:43 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PQ40D084
[Fri Jul 15 2022 15:55:43 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 15:55:58 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03P732QHB9
[Fri Jul 15 2022 15:55:58 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 15:56:03 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PQ421CE8
[Fri Jul 15 2022 15:56:03 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
[Fri Jul 15 2022 15:56:14 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03P73675L7
```

**Comment by seratch** [comment]
Hi @yihchu, this is not a usual situation at all. I would suggest printing the message using console.log() or logger.info() to figure out where the events are coming from.

**Comment by yihchu** [comment]
> ould suggest printing the me
Hi @seratch , how to print where the events coming from ?

**Comment by yihchu** [comment]
Hi, @seratch , you can see the logs, you can see `Received file_shared message from: undefined`, why it is undefined?

**Comment by seratch** [comment]
@yihchu Thanks for sharing this. The undefined user ID part in the debug-level logging seems to be a bug on the hubot-slack side. We may improve this in future releases.

The easiest way to print the event data would be to add the following `robot.listen` code at the top of your code:
```coffeescript
module.exports = (robot) ->
  robot.listen(
    (message) -> console.log(JSON.stringify(message, null, 2))
    (response) ->
  )
```
