### ISSUE TITLE
unable to get response from hubot

### ISSUE THREAD

**Issue by mitthat29** [slackapi/hubot-slack#646]
### Description

I have been trying to configure chatops with slack but unfortunately I am not able to set up connectivity between the two. The reason could be that I am using a private server(specific to my organization which can only be accessed with VPN) and Slack is a public one. I tried doing the same with a public server and it worked for me. Please let me know if there is a way to establish connectivity between a private server and slack.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @mitthat29, thanks for writing in!

I am unsure about what you mean by "private server" here but hubot-slack connects to Slack server throughout an outgoing WebSocket connection. Thus, as long as your "private server" allows your hubot app to establish a WebSocket connection to the internet, your hubot should work. If your "private server" does not allow your apps to establish an outgoing connection, there is no way to connect to Slack from the environment.

Also, if you are planning to develop a new app, we no longer recommend using hubot-slack for it. Please consider going with the latest feature called Socket Mode, which provides equivalent functionalities:
* https://slack.dev/bolt-js/concepts#socket-mode
* https://slack.dev/node-slack-sdk/socket-mode

I hope this was helpful to you.

**Comment by mitthat29** [comment]
> Hi @mitthat29, thanks for writing in!
> 
> I am unsure about what you mean by "private server" here but hubot-slack connects to Slack server throughout an outgoing WebSocket connection. Thus, as long as your "private server" allows your hubot app to establish a WebSocket connection to the internet, your hubot should work. If your "private server" does not allow your apps to establish an outgoing connection, there is no way to connect to Slack from the environment.
> 
> Also, if you are planning to develop a new app, we no longer recommend using hubot-slack for it. Please consider going with the latest feature called Socket Mode, which provides equivalent functionalities:
> 
> * https://slack.dev/bolt-js/concepts#socket-mode
> * https://slack.dev/node-slack-sdk/socket-mode
> 
> I hope this was helpful to you.

Thanks for your reply. I will look into it.

**Comment by seratch** [comment]
Thanks for your reply! Let us close this issue now.
