### ISSUE TITLE
App user who is initiating action is identified as channel instead of App name

### ISSUE THREAD

**Issue by psugne** [slackapi/hubot-slack#647]
### Description

Since I updated `hubot-slack` till the newest version [v4.10.0](https://github.com/slackapi/hubot-slack/releases/tag/v4.10.0) and recreated Hubot App for Slack I noticed, that Drone app which posts on slack channels (started with `!`) via [incoming webhooks](https://api.slack.com/messaging/webhooks) is identified as `channel` user instead of `Drone` user. When regular user initiates an action on channel he is identified correctly. User identification in written on `/actions` dir on `*.yaml` file with with identification - `action_context.api_user`. So I can't identify why it's happening and how I could fix it to get user I needed (`Drone`, app user) instead of `channel` which is not what's expected.

e.g.
```
parameters:
    api_user:
        type: "string"
        description: "API User"
        required: true
        default: "{{action_context.api_user}}"
        position: 0
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.10.0

node version: v6.17.1

OS version(s): Ubuntu 16.04 LTS

#### Steps to reproduce:

1. Add Drone app to your Workspace
2. Create an incoming webhook for specific channel
3. Post a chatops message on channel (e.g. mine was `!deploy 14.0`) by using incoming webhook

#### Expected result:

Drone app is identified as `Drone` user

#### Actual result:

Drone app was identified as `channel` user
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.
![chatops](https://user-images.githubusercontent.com/17007193/191219113-dcf4df88-b51a-44d8-9d77-6eabe76eba3d.png)

**Comment by seratch** [comment]
Hi @psugne, thanks for writing in!

I am unfamiliar with the Drone app, but the issue described here seems to be related to how your stormtrooper app on top of hubot and hubot-slack generates the reply message including the mention. If your app mentions the channel, the format of the part should be `<!channel>`. Indeed, your app code might be affected by some recent changes on the hubot-slack side, but hubot-slack itself does not have any feature to generate channel mentions for you.

To identify the difference between Drone app messages and human messages, I'd suggest adding the following listener at the top of your code to dump the actual payload data. With that, you can get more detailed information about what's going on under the hood. If you see anything wrong on the hubot-slack side, please let us know the details of the misbehavior.

```coffeescript
module.exports = (robot) ->
  robot.listen(
    (message) -> console.log(JSON.stringify(message, null, 2))
    (response) ->
  )
``` 

I hope this was helpful to you.

**Comment by psugne** [comment]
> Hi @psugne, thanks for writing in!
> 
> I am unfamiliar with the Drone app, but the issue described here seems to be related to how your stormtrooper app on top of hubot and hubot-slack generates the reply message including the mention. If your app mentions the channel, the format of the part should be `<!channel>`. Indeed, your app code might be affected by some recent changes on the hubot-slack side, but hubot-slack itself does not have any feature to generate channel mentions for you.
> 
> To identify the difference between Drone app messages and human messages, I'd suggest adding the following listener at the top of your code to dump the actual payload data. With that, you can get more detailed information about what's going on under the hood. If you see anything wrong on the hubot-slack side, please let us know the details of the misbehavior.
> 
> ```coffee
> module.exports = (robot) ->
>   robot.listen(
>     (message) -> console.log(JSON.stringify(message, null, 2))
>     (response) ->
>   )
> ```
> 
> I hope this was helpful to you.

@seratch thank you for a quick reply. User who posted deploy message is wrong. Actually `Drone` user should post it.

Regarding debugging, please let me know where exact I could include this code snipped you provided to me. Would it be _hubot-slack_ code somewhere or mine own code?

**Comment by seratch** [comment]
@psugne I meant that you can add the listener in your own Hubot app code.
