### ISSUE TITLE
Port hubot-slack away from @slack/client?

### ISSUE THREAD

**Issue by a-ungurianu** [slackapi/hubot-slack#648]
### Description

[@slack/client]() is marked as deprecated in npm but it still is the underlying API for this adapter.

Are there plans to update this adapter to utilize the new APIs, or is the future expectation to move to Bolt directly, and not utilize hobot all together?

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hi @a-ungurianu, thanks for writing in!

>Are there plans to update this adapter to utilize the new APIs, or is the future expectation to move to Bolt directly, and not utilize hobot all together?

No, there aren't unfortunately. hubot-slack is in its maintenance mode and we won't actively develop it anymore. For new app development, we highly recommend going with either [Bolt for JS with Socket Mode](https://slack.dev/bolt-js/concepts#socket-mode) or [our next-generation beta platform on Deno runtime](https://api.slack.com/future).

**Comment by a-ungurianu** [comment]
Thanks for updating the Readme. I'll have a look at Blot soon.
