### ISSUE TITLE
Rtm.start not getting replaced by rtm.connect

### ISSUE THREAD

**Issue by somali3395** [slackapi/hubot-slack#649]
Hi Team,

We have developed a bot in slack using Hubot. Now that rtm.start api is deprecated , we are unable to start hubot as it throws error like : Unable to start rtm.start. I have tried setting the environment variable to rtm.connect as suggested like export HUBOT_SLACK_RTM_CLIENT_OPTS='{"useRtmConnect": "true"} , but it still throws me the same error. I have attached the screenshot of the error here. Looks like its still using the rtm.start api. Could you help me in this? where exactly is this rtm.start api and how do i replace it with rtm.connect?
![image001](https://user-images.githubusercontent.com/118369652/202618073-7deb1415-1a25-48e9-b925-255b5840dc0c.png)

**Comment by seratch** [comment]
Hi @somali3395, thanks for asking the question. It seems that your env variable is not loaded in hubot-slack for some reason. Perhaps, you may be using a bit old version, which does not support the option.

The best way to resolve this is to upgrade to the latest version. v4.10.0 uses rtm.connect by default, so that you don't need to pass any extra options: https://github.com/slackapi/hubot-slack/releases/tag/v4.10.0

**Comment by somali3395** [comment]
Hi @seratch , Thanks for your help. 
I am using this documentation https://slack.dev/hubot-slack/ to create a BOT in slack. This guides me to install the following package "generator-hubot" .This is the latest versions that i updated. i am  still getting the rtm.start error. 
![Uploading gg.PNG…]()

**Comment by somali3395** [comment]
![gg](https://user-images.githubusercontent.com/118369652/202889354-3ed65e4b-4f6e-4861-a934-29226ddad1f3.PNG)

**Comment by seratch** [comment]
@somali3395 Just in case, I've confirmed the latest version works without any issues. All I did was:
* Head to https://my.slack.com/apps/A0F7XDU93-hubot and generate a new setting
* `npm install -g yo generator-hubot`
* `mkdir my-awesome-hubot && cd my-awesome-hubot`
* `yo hubot --adapter=slack`
* `HUBOT_SLACK_TOKEN=(your token here) HUBOT_LOG_LEVEL=debug ./bin/hubot --adapter slack`

As you can see, I followed the instructions here: https://slack.dev/hubot-slack/#basic-setup and it worked for me.

I am guessing that your app may still be using an older version for some reason.  Please make sure the version is v4.10.0 for sure. When you start your hubot app, you can find the following line in the stdout outputs:

```
[(datetime here)] INFO hubot-slack adapter v4.10.0
```

Also, enabling debug-level logging may help you figure out the cause of your situation. You can run your app with debug-level logging by the following option. Refer to https://slack.dev/hubot-slack/advanced_usage#activate-logging-for-debugging for more details.

```bash
HUBOT_SLACK_TOKEN=(your token here) HUBOT_LOG_LEVEL=debug ./bin/hubot --adapter slack
```

**Comment by somali3395** [comment]
Hi @seratch . Thank you for your reply. I am getting this error while running yo hubot --adapter=slack. Which version of node and npm are you using?
![ty](https://user-images.githubusercontent.com/118369652/203007477-dba7f4e4-9404-4149-933e-c60e9578c55b.PNG)

**Comment by somali3395** [comment]
Hi @seratch Thank you so much for your help. It worked
