### ISSUE TITLE
slack bot respond only once in the thread message

### ISSUE THREAD

**Issue by prashanth-cbsi** [slackapi/hubot-slack#650]
### Description

Do not invoke/respond to the messages in a thread, need help to implement the logic

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.10.0

node version: 19.4.0

OS version(s): 

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by srajiang** [comment]
@prashanth-cbsi - Are you having a specific issue using the hubot tool or looking for assistance in designing / implementing your app?  👋 If it's the former, could you please provide a bit more information about how your app is currently setup (code samples are great as well as any logs), what behavior you'd like to see and what you're currently seeing? 

If you're just getting started with developing and are more looking for advice on how to implement your use case I'd recommend taking this issue to our community Slack (anyone can join) [community.slack.com](community.slack.com)
