### ISSUE TITLE
Deleted Message Event

### ISSUE THREAD

**Issue by nirajpatel** [slackapi/hubot-slack#654]
### Description

Hi there! I'm using Hubot to monitor messages that are being sent in Slack channels. Is there a way to monitor messages that have been deleted? I haven't been able to find a way to do so reading through the documentation and code. Thanks for the help in advance!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @nirajpatel, thanks for your question. 

As you may know, the Slack adapter for Hubot connects to Slack using the RTM (Real Time Messaging) mechanism. The RTM itself delivers 'message_deleted' subtype events to connected clients: https://api.slack.com/events/message?filter=RTM. However, this Hubot adapter only sends newly posted message events to your Hubot scripts: https://github.com/slackapi/hubot-slack/blob/v4.10.0/src/bot.coffee#L262-L283.

So, unfortunately, there's no way to achieve your goal with Hubot, and we don't have plans to enhance the library in the future. We recommend using an Events API-based approach instead. For more details, take a look at the Bolt frameworks (https://api.slack.com/tools/bolt). 

I hope this information is helpful!

**Comment by nirajpatel** [comment]
@seratch that's very helpful. Thank you! :)
