### ISSUE TITLE
Make hubot help private message?

### ISSUE THREAD

**Issue by njia** [slackapi/hubot-slack#82]
any chance to make hubot responds help with a private message ? Looks like it has been done for hubot-irc adaptor.

**Comment by Shy** [comment]
@grantmd Did this make it into a the release. I'm not seeing any mentions on how to enable this feature while searching through the issues in github.

**Comment by msabramo** [comment]
I've seen some mentions that they released a new version of hubot-slack that supports this, but I don't know if there's some special config I need to do, because I can't invite my hubot to private conversations.

**Comment by stevemcquaid** [comment]
+1 to @msabramo
