### ISSUE TITLE
access to user's email address

### ISSUE THREAD

**Issue by JonBoley** [slackapi/hubot-slack#93]
I'm new to both Hubot and Slack, but is there a way to access `msg.message.user.email_address`?
For example, I'd like to do stuff like [this](https://github.com/github/hubot-scripts/blob/master/src/scripts/achievement_unlocked.coffee), which doesn't appear to grab the email address in Slack...

**Comment by JonBoley** [comment]
How should I be able to access the `email_address` field now? (I'm assuming this has been deployed.)

`msg.message.user` and `msg.envelope.user` both appear to contain only this info

```
user: 
     { id: 'XXXXXXXXX',
       name: 'XXXXXX',
       reply_to: 'XXXXXXXXX',
       room: 'XXXX' }
```

**Comment by Cinetik** [comment]
@JonBoley Any news on that?

**Comment by JonBoley** [comment]
@Cinetik I never did figure that out

**Comment by patcon** [comment]
@Cinetik @JonBoley seems this might be related: https://github.com/slackapi/hubot-slack/issues/367#issuecomment-258242805
